backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponTemplate.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Member.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/support/DatabaseCleaner.java

- 모든 테이블의 PK 컬럼을 id로 통일
- 테스트 DB 리셋시키는 TRUNCATE문 수정
많은 도메인을 건들이기 때문에 미리 작업하여 올립니다.
Resolves #35

refactor: PK 컬럼 id로 통일

---

backend/src/docs/asciidoc/index.adoc
backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Member.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/repository/MemberRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/exception/member/MemberDuplicatedEmail.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/MemberCreateRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/Documentation.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java
backend/src/test/java/com/woowacourse/kkogkkog/fixture/MemberFixture.java

- 회원가입 API 구현
- Member 엔티티 변경
- 회원가입 API 구현
- Test Code에 Fixture 도입
- 프론트와 같이 페어 코딩
Resolves #30

feat: 회원가입 API 구현

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MembersResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java

- 회원가입 된 회원들의 전체 목록을 조회하는 API 구현
- 로그인을 했을 경우만 API를 호출할 수 있도록 할지 추후 검토한다.
- 인수테스트가 기존 작성법과 다름. 추후 refactor 브랜치를 통해서 `@Nested`를 통한 DCI 패턴 기반의 작성을 논의한다.
- 기존 fixture 들을 활용하지 않음. 추후 refactor 브랜치를 통해서 'fixture'들의 활용법을 논의한다.
Resolves #31

feat: 회원가입 된 회원들의 전체 조회 API 구현

---

backend/src/docs/asciidoc/coupon.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponChangeStatusRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/config/InterceptorConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponStatus.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponEventRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponStatusTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java

- 상태 변경 요청에 대한 도메인, 서비스, API 틀 구현
- 쿠폰 사용 요청 기능 구현
- REST DOCS 추가
신규 기능에 대한 도메인별 커스텀 예외클래스는 아직 구현하지 않았습니다. 상태코드만 제대로 나오도록`InvalidRequestException`, `ForbiddenException` 등의 클래스를 그대로 사용하였습니다. 
컨틀롤러와 서비스의 메서드명에 대해 고민 중입니다. 다음 쿠폰 사용 거절 요청 기능 구현할 때 수정해서 확정해주었으면 좋겠습니다.
Resolves #69

feat: 쿠폰 사용 요청 API 구현

---

backend/src/main/java/com/woowacourse/kkogkkog/exception/GlobalControllerAdvice.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/AuthController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponCreateRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/MemberCreateRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/TokenRequest.java

- 모든 API들의 RequestBody 필드 내 Spring Bean Validation 적용함
- validation에 의해 검증에 실패하면 MethodArgumentNotValidException을 반환하나 세부 커스텀 예외로 핸들링하지는 못하고  
InvalidRequestException을 호출하도록 구현함
- 이메일과 패스워드 등 정규식은 구현하지 않음. 빈 문자열인지만 검사함.
- 스타일 가이드 통일 요청.
Resolves #70

feat: Spring Bean Validation 도입

---

frontend/src/@hooks/user/useMe.ts
frontend/src/@pages/landing/index.tsx
frontend/src/Router.tsx
frontend/src/apis/user.ts

- Login API 연동했습니다.
`client.defaults.header['Authorization']` 코드가 잘 동작하는데, 타입에러는 떠서 어떻게 해야할지 하하~
- PublicRoute 구현하여 씁니다.
아직, 인가 처리에 대한 고민을 공유하지 않았지만, 코드가 간단해서 일단 심어둡니다.
- LandingPage를 UnAuthorizedLanding과 AuthorizedLanding으로 분리했습니다.
그 이유는 하나의 컴포넌트 안에서 분기처리를 해버리면 hook을 early return할 수 없으므로, useKkogKkogList 같은 데이터 패칭 훅을 무조건 실행하게 됩니다. 하지만, UnAuthorizedLanding 는 데이터 패칭 훅이 필요없습니다. 그래서 컴포넌트를 분리했고 필요한 곳에서만 훅을 선언하도록 했습니다.
- 코드는 간단한데 생각보다 시간이 오래걸렸는데요. Suspense 를 걸어주고
- Landing 에서 getMe가 통신하는 동안 UnAuthorizedLanding 을 보여줘야할지 AuthorizedLanding를 보여줘야할지 판단할 수 없습니다. 현재 상황에서는 UnAuthorizedLanding이지만, AuthorizedLanding의 Skeleton을 보여주기도 하고, AuthorizedLanding이지만, UnAuthorizedLanding가 처음에 반짝 렌더링되는 현상이 있었습니다. 이를 해결하고자, getMe 통신에도 Suspense를 걸어서, Landing에 Loading처리를 해주려고 했습니다. 하지만, useMe를 suspense true로 만드니 갑자기 …

feat: Login API 연동 및 인가 처리

---

backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponStatus.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponStatusTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java

- 받은 사람(Receiver)이 쿠폰 사용 요청을 취소하는 기능 구현
기존 CouponEvent 에서 of 를 사용할 때 null 이 넘어오면 NPE 가 발생하는 문제도 같이 수정했습니다.
Resolves #83

feat : 쿠폰 사용 요청 취소 API 구현

---

backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponType.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponControllerTest.java

- 사용자의 쿠폰 목록 조회시 받은 쿠폰과 보낸 쿠폰 반대로 조회되는 문제 해결
- 프론트에는 존재하지만 백엔드에는 누락된 쿠폰 타입 DRINK 추가
Resolves #87

fix: 쿠폰 목록 조회 버그 수정

---

frontend/src/@components/@shared/CustomSuspense/index.tsx
frontend/src/@components/@shared/ListFilter/index.tsx
frontend/src/@components/@shared/ListFilter/style.tsx
frontend/src/@components/kkogkkog/KkogKkogList/index.tsx
frontend/src/@components/kkogkkog/ReceivedKkogKkog/index.tsx
frontend/src/@components/kkogkkog/SentKkogKkog/index.tsx
frontend/src/@hooks/@common/useRouterState.ts
frontend/src/@hooks/kkogkkog/useKkogKkogList.ts
frontend/src/@hooks/user/useMe.ts
frontend/src/@pages/landing/index.tsx
frontend/src/Router.tsx
frontend/src/types/utils.ts

랜딩 페이지 Suspense 처리
CustomSuspense 컴포넌트를 개발하여 React.Suspense 컴포넌트가 할 수 없는 동작을 하도록 구현한다.
Skeleton UI들을 추가적으로 개발, 개선한다.
router의 state를 잘 활용해보자
useRouterState 훅을 개발하여 Router 의 state를 활용하는 코드를 더 이해하기 쉽도록한다.
정적 Typing을 추가한다.(다음 풀리퀘에서 진행)
Resolves #97

feat: 랜딩 페이지 Suspense 처리, router의 state를 잘 활용해보자

---

backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponStatus.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponStatusTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java

쿠폰 사용 요청을 수락하는 기능 구현
- CouponEvent enum에 ACCEPT 이벤트 추가
- CouponStatus enum에 ACCEPTED 상태 추가
- 쿠폰 사용 요청 수락에 대한 테스트 작성
테스트는 우선 기존 틀에 맞춰서 작성했습니다.
Resolves #93

feat : 쿠폰 사용 요청 수락 기능 구현

---

backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponStatus.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponStatusTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java

- 보낸 사람(Sender)과 받은 사람(Receiver)이 쿠폰 사용을 완료하는 기능 구현
- CouponTest는 보낸 사람과 받은 사람 모든 경우 구현
- CouponTest 구현하다 어느정도 테스트 해야될까 아서와 이야기했습니다. 그래서 CouponServiceTest는 보낸 사람일 경우의 테스트만 구현해 봤습니다. 의견 남겨주시면 감사하겠습니다.
Resolves #109

feat : 쿠폰 사용 완료 API 구현

---

.github/workflows/pull-request-ci.yml

최소한의 CI 과정을 추가하였습니다.
PR이 생성되는 시점에 두 가지 job이 실행되도록 설정하였습니다. frontend 디렉토리의 프로젝트에 대해 `yarn build`를 실행하고, backend 디렉토리의 프로젝트에 대해서는 `./gradlew build`를 실행합니다.
예를 들어, 해당 yml 파일이 main 브랜치에 머지된 상태에서 main 브랜치에 대한 PR이 생성되었을 때, PR 하단에 아래와 같은 내용이 돌아갈 것입니다.
해당 깃헙 액션이 성공하면 PR 옆에 아래와 같이 녹색 체크가 표시될 것입니다.
실행되면서 출력되는 로그는 Actions 탭에서 확인할 수 있습니다.
슬랙 깃헙봇에서도 다음과 같이 표시됩니다.
Resolves #123

config: 깃헙 액션을 통해 PR에 대해 CI 설정 

---

frontend/src/@components/@shared/ToastProvider/index.tsx
frontend/src/@components/@shared/ToastProvider/style.tsx
frontend/src/@hooks/@common/useToast.ts
frontend/src/@hooks/user/useAuthenticateForm.ts
frontend/src/index.tsx

- Toast UI를 개발하였습니다.
[애니메이션 참고 사이트](https://animista.net/play/entrances/slide-in-blurred/slide-in-blurred-bottom)
- gif
1. Toast UI를 사용할 컴포넌트를 ToastProvider 컴포넌트로 감싸준다. (우리한텐 `App` 컴포넌트)
2. ToastProvider로 감싼 컴포넌트의 자식 컴포넌트 들에서 useToast를 호출하면 `displayName` 이라는 Toast UI 트리거 함수를 받아낼 수 있다.
3. 이를 받아내 호출하면 끝!
```jsx
// index.jsx
import { Global, ThemeProvider } from '@emotion/react';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from 'react-query';
import ToastProvider from '@/@components/@shared/ToastProvider';
import App from '@/App';
import globalStyle from '@/styles/globalStyle';
import theme from '@/styles/theme';
if (process.env.NODE_ENV === 'development') {
const { worker } = require('./mocks/browser');
worker.start();
} …
```

feat: Toast UI 개발

---

frontend/src/@components/@shared/CustomSuspense/index.tsx
frontend/src/@components/@shared/ToastProvider/style.tsx
frontend/src/Router.tsx

- 인증되어 있는 경우에도 인증되어 있지 않은 경우와 동일하게 동작하던 이슈
- 요청 중에 `Navigate` 컴포넌트에 의해 라우팅되어 이슈가 발생
- isLoading을 통해 `Suspense` 처리를 추가함
Resolves #이슈번호

refactor: 인가 기능 수정

---

backend/build.gradle
backend/src/main/resources/application.yml

- Spring Profile 적용
- application.yml 구분
- prod 프로파일을 사용하면 MySQL DB를 사용하도록 설정
- MySQL DB 셋업
- prod용 & dev용 계정과 database 분류하여 생성 완료
- 현재 prod EC2 인스턴스의 deploy.sh 스크립트 실행시, prod 프로파일 사용하여 prod DB 연동되어 실행되도록 설정하였습니다.
- 현재 dev EC2 인스턴스의 deploy_with_db.sh 스크립트 실행시, prod 프로파일 사용하여 dev DB 연동되어 실행되도록 설정하였습니다.
- DB 정보 및 프로파일 활용 방법은 노션으로 공유할 예정입니다.
- OAuth로 전환하게 되면 환경변수를 다루기 필요할 것 같아 스프링 프로파일 형식을 셋업하였습니다.
Resolves #120

chore: MySQL DB 마이그레이션 및 Spring Profile 적용

---

backend/src/main/java/com/woowacourse/kkogkkog/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponChangeStatusRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/config/InterceptorConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponEventRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponRequestEventRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java

- 쿠폰 사용 요청 시 날짜를 입력받는 기능
- REQUEST 이벤트 api 분리
- 해당 API에서만 날짜를 입력받도록 변경
- 쿠폰 조회 시 쿠폰 사용 날짜를 조회하는 기능
- 단일 조회, 전체 조회에서 쿠폰 사용 날짜를 조회하도록 변경
일단 기능만 구현한 상태고 내일 전체 리팩토링 과정에서 변경될 내용입니다~!
Resolves #128

feat: 쿠폰 사용 요청 및 조회시 날짜를 추가하는 기능

---

.github/workflows/pull-request-ci.yml

- 현재 PR이 처음에 생성된 시점 + 닫혔다가 다시 열린 시점에만 CI가 동작하도록 설정된 상태입니다.
- PR을 draft로 생성한 경우, 리뷰 가능한 상태로 전환될 때에도 CI가 동작하도록 설정할 필요성이 확인되어 관련 조건을 추가했습니다.

chore: 리뷰 가능 상태로 전환된 draft PR에 대한 CI 트리거 추가

---

frontend/src/@components/coupon/CouponItem/big.tsx
frontend/src/@components/coupon/CouponItem/small.tsx
frontend/src/@components/coupon/CouponModal/index.tsx
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/coupon/useChangeCouponStatus.ts
frontend/src/@hooks/coupon/useCouponForm.ts
frontend/src/@hooks/user/useAuthenticateForm.ts
frontend/src/@hooks/user/useSearchUser.ts
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/@pages/login/redirect.tsx
frontend/src/@pages/profile/index.tsx
frontend/src/Router.tsx

- useQuery 기반의 훅 동작 수정
- 모든 데이터를 그대로 반환한다에 대한 고민이 필요합니다.
- 데이터를 일부 가공해서 주기도 합니다. (가공된 데이터 + 날 것 그대로의 데이터를 반환합니다.)
- useMutation 훅 
- navigate 로직은 비즈니스 로직 훅 혹은 컴포넌트에서 결정합니다.
- toast 로직은 단순 에러를 출력하기에 useMutation 훅에 강하게 결합시켰습니다.
- useMutation 기반의 비즈니스 로직 훅 수정 
- 이 훅으로 성공 로직, 실패 로직을 컴포넌트 단에서 주입할 수 도 있습니다. ( 이 경우 성공 로직, 실패 로직은 컴포넌트 UI 로직으로 한정됩니다. ) 
강조되는 규칙
컴포넌트는 `useMutation 기반의 커스텀 훅`을 호출하거나, 비즈니스 로직 훅을 호출하여 비즈니스 로직을 수행합니다. ( 컴포넌트가 직접 `useMutation 기반의 커스텀 훅`을 호출하는 경우는 드물지만 컴포넌트와 비즈니스 로직의 결합도가 강한 경우 허용합니다.)
컴포넌트는 `useQuery 기반의 커스텀 훅` 훅을 호출할 수 있습니다. 이 경우 가공된 데이터 + 날것 그대로의 데이터를 반환받고, `useQuery`가 반환하는 모든 데이터를 전달받습니다. ( 모든 데이터를 전달받는다에 대한 고민이 필요합니다. `refetch, remove` 같은 함수들은 섬세하게 다루어줄 필요가 있다고 생각됩니다.
Resolves #105

refactor: 중간 리팩터링 - react query 기반의 훅 구조 리팩터링

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberUpdateRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/config/InterceptorConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Member.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/MemberNicknameUpdateRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/MemberUpdateMeRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java

- 사용자의 닉네임을 수정하는 기능 구현
기능 구현 완료 후 회원 인수 테스트의 메서드를 분리하고 MemberController 메서드의 순서를 정렬하였습니다.
Resolves #149

feat: 사용자 닉네임 수정 기능 구현

---

backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponMemberResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Member.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/SlackUserInfo.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/AuthServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/fixture/MemberFixture.java

- 사용자 도메인에 email 필드 추가
- 사용자, 쿠폰 관련 API들 응답에 email 정보 추가 
- 슬랙 로그인시, 프로필과 함께 이메일도 함께 자동 업데이트되도록 설정
- Member 도메인 수정이 좀 많이 힘드네요.
- REST DOCS에 수식어, 배경색이 있다거나, 테스트의 DisplayName 내용이라던가 짜잘하게 수정하고 싶은게 계속 보이네요.
Resolves #155

feat: 사용자 도메인에 email 필드 추가

---

backend/src/main/java/com/woowacourse/kkogkkog/application/AuthService.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Workspace.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/repository/WorkspaceRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/exception/auth/BotInstallationFailedException.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/BotTokenResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/SlackClient.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/WorkspaceResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/AuthController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/InstallSlackAppRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/AuthServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/SlackClientTest.java

- 사용자의 워크스페이스에 앱을 등록
- Slack 인증 서버에 워크스페이스 봇 토큰을 요청하는 기능 구현
- 봇 엑세스 토큰 저장 요청 API 구현
- 워크스페이스 아이디, 이름, 봇 엑세스 토큰을 가지는 Workspace 엔티티 구현
Restdocs 아직 미작성
Resolves #157

feat: Slack Workspaces 앱 등록 기능 구현

---

backend/src/docs/asciidoc/auth.adoc
backend/src/docs/asciidoc/coupon.adoc
backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberHistoryResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/config/InterceptorConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/MemberHistory.java
backend/src/main/java/com/woowacourse/kkogkkog/exception/member/MemberHistoryNotFoundException.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/MemberHistoryTest.java

- 사용자가 알림함을 상세 조회할 경우 방문 여부가 변경되는 기능을 구현
해당 PR에서 기능과 무관하게 변경된 부분이 있습니다!!
- /api/history -> /api/histories
- 사용되지 않은 컬럼 임시로 nullable 제거
Resolves #164

feat: History 방문 여부에 대한 방문 상태 변경 기능

---

backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MyProfileResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/repository/MemberHistoryRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/main/resources/application.yml
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/repository/MemberHistoryRepositoryTest.java

- 기존에 존재하는 본인 정보 조회 API에 읽지 않은 알림 개수 정보를 포함시킴
- prod 프로파일로 배포시, 스키마 검증을 실행하지 않도록 수정
`MemberHistoryRepositoryTest`를 만든 이유는 
1) `countByHostMemberAndIsReadFalse` 메서드의 정상동작 여부를 다른 테스트에 포함시키자니 너무 더러워져서 
2) 그리고 쿠폰을 보낸 사람과 받은 사람이 `MemberHistoryRepository` 도메인의 hostMember & targetMember에 어떻게 대입되는지 설명을 좀 남기고 싶어서입니다.
Resolves #166

feat: 본인 정보 조회 API에 읽지 않은 알림 개수 정보 포함

---

backend/src/main/java/com/woowacourse/kkogkkog/KkogKkogApplication.java
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberHistoryResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/BaseEntity.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/MemberHistory.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/repository/MemberHistoryRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/Documentation.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java

- MemberHistory에 createdAt를 추가
- BaseEntity 생성
- createdAt 컬럼 추가
추후 모든 Entity가 LocalDateTime을 가질 예정입니다
Resolves #172

feat: MemberHistory Entity에 createdAt를 추가

---

.github/workflows/pull-request-ci.yml
backend/build.gradle

구구와의 끈밀한 협업을 통해 해당 깃헙 저장소에 Sonar Cloud 앱 설치를 하였으며, 깃헙 CI용 토큰을 전달받은 상황입니다.
[소나클라우드 사이트의 대쉬보드](https://sonarcloud.io/organizations/woowacourse-teams/projects)에서 프로젝트 조회 가능합니다.
트리거 관련하여 수정하기 전에 제대로 동작하는지 체크해보기 위해 미리 PR 올려봅니다.
Resolves #191

chore: SonarCloud CI 워크플로우 셋업

---

backend/src/main/java/com/woowacourse/kkogkkog/application/AuthService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Member.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/MemberUpdateMeRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/MemberTest.java

- 회원가입시 "익명1234"와 같은 형식의 닉네임을 임의로 생성하여 DB에 데이터를 저장하도록 수정.
- FE에서는 신규 회원이 생성되었다는 정보를 통해 닉네임 수정 페이지로 즉시 리다이렉트시키므로, 일반적인 flow상 회원은 자신의 닉네임을 모름.
- 향후 닉네임 수정시, `^[가-힣a-zA-Z0-9]{2,6}$`라는 정규표현식에 부합하는지를 검증.
- 닉네임 수정 API에 빈 값이 들어오거나 null이 들어오면 예외 발생하도록 Bean Validation 추가.
- 닉네임 수정 API에 들어온 입력 값이 "   정    "와 같이 앞뒤에 공백이 포함된 경우, 공백 제거하여 저장하도록 DTO에서 trim
Member 자체에 방어로직을 추가하는 경우, 테스트가 너무 깨져서 일단은 닉네임 수정에 대해서만 로직을 추가하였습니다.
Resolves #201

feat: 닉네임에 대해 정규표현식 적용 및 회원가입시 임의의 닉네임 생성 

---

frontend/package.json
frontend/src/@hooks/@common/useInput.ts
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/requesst/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/requesst/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/style.tsx
frontend/src/styles/globalStyle.ts
frontend/src/utils/index.ts

- input date를 클릭하면 무조건 calandar 가 뜨도록
- 모든 input 글자 16 px로 맞추어서 zoom 안되도록 하는 것
- input date 오늘 이전 날짜 선택하지 못 하도록 validation 추가 (사파리에서 min 을 지원하지 않기 때문)
- build:local script 명령어 추가
Resolves #183

feat: date input 크로스 브라우징 대응

---

backend/src/main/java/com/woowacourse/kkogkkog/KkogKkogApplication.java
backend/src/main/java/com/woowacourse/kkogkkog/config/DatabaseConfig.java
backend/src/test/java/com/woowacourse/kkogkkog/common/annotaion/RepositoryTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/domain/query/CouponQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/kkogkkog/support/DataClearExtension.java

- @RepositoryTest에서 DB 초기화하도록 설정
- @RepsitoryTest에서 DatabaseCleaner 빈을 직접 주입했을 때 접근할 수 있도록 DataClearExtension의 빈 가져오는 로직 수정
- @RepsitoryTest에서 SpringApplication 전체를 실행하지 않아도 @EnableJpaAuditing 설정되도록 별도의 DatabaseConfig 구현하여 주입하도록 수정. (prod에서는 @Configuration 설정하여 알아서 ComponentScan 대상 되도록 설정)
- 영속성 컨텍스트에 Workspace를 저장하고 Member에 연관관계로 설정해야 하는 부분 수정
현재 develop 브랜치 깨지고 있는 상황이기는 한데 수정한 부분이 많은 것 같아서 별도의 PR로 만들었습니다.
Resolves #219

hotfix: 깨지는 RepositoryTest 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberHistoryResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponHistoryResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/BaseEntity.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/MemberHistory.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/repository/MemberHistoryRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/reservation/domain/Reservation.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/reservation/application/ReservationServiceTest.java

- MemberHistory의 createdAt을 created_time으로 통일
- createdTime과 updatedTime을 사용하는 도메인들의 경우 실수 예방을 위해 BaseEntity 상속받도록 수정
- MemberHistory는 update될 일이 없어서 BaseEntity 상속받도록 설정하지 않았는데, 실수가 발생할 수 있는 구조가 아닌가 싶네요.

hotfix: created_time으로 필드명 통일

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/SlackClient.java

- 엑세스 토큰 요청시 사용하는 SlackClient의 리다이렉트 uri를 삭제한다.
Resolves #227

refactor: 필요없는 SlackClient redirect uri 삭제

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/SlackClient.java
backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/SlackClientTest.java

- submodule 수정 없이 일단 내부적으로 수정
- 정상 동작 확인 이후에 yml에서 받아오도록 리팩토링

hotfix: 동작하는 profile에 따라 SlackClient에 다른 redirect url들 설정

---

frontend/src/@components/@shared/ListFilter/style.tsx
frontend/src/@components/@shared/Placeholder/index.tsx
frontend/src/@components/coupon/AcceptedCouponList/index.tsx
frontend/src/@components/coupon/AcceptedCouponList/style.tsx
frontend/src/@components/coupon/CouponItem/big.style.tsx
frontend/src/@components/coupon/CouponItem/big.tsx
frontend/src/@components/coupon/CouponItem/small.style.tsx
frontend/src/@components/coupon/CouponItem/small.tsx
frontend/src/@components/coupon/CouponStatus/index.tsx
frontend/src/@components/coupon/CouponStatus/style.tsx
frontend/src/@components/reservation/ReservationItem/index.tsx
frontend/src/@components/reservation/ReservationItem/style.tsx
frontend/src/@components/reservation/ReservationList/index.tsx
frontend/src/@components/reservation/ReservationList/style.tsx
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@pages/coupon-list/create/index.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/styles/globalStyle.ts

- 쿠폰 UI를 강화
- 쿠폰 리스트 페이지의 카테고리에서 쿠폰 상태를 표현한다.
- 쿠폰에는 상태 워딩 대신 날짜가 표현된다.
- 대기 중인 쿠폰에는 아무런 표식이 없다.
- 쿠폰 UI의 비율이 사라진다. 고정 높이만이 존재하고 좌우 너비는 280~340로 자유롭게 가질 수 있다.
- 승인된 섹션
- 승인된 쿠폰들이 날짜 별로 보인다. 
- 쿠폰 UI -> 예약 UI로 대체한다.
Resolves #185

feat: Coupon UI 변경

---

backend/src/main/java/com/woowacourse/kkogkkog/reservation/application/dto/ReservationSaveRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/reservation/presentation/dto/ReservationCreateRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/PushAlarmListenerTest.java
backend/src/test/java/com/woowacourse/kkogkkog/common/fixture/dto/ReservationDtoFixture.java
backend/src/test/java/com/woowacourse/kkogkkog/core/reservation/acceptance/ReservationAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/reservation/application/ReservationServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/reservation/documentation/ReservationDocumentTest.java

프론트에서 받아오는 날짜 객체를 LocalDateTime이 아닌 LocalDate로 받도록 수정하였습니다.
- Request Dto 날짜 타입 변환
- LocalDateTime -> LocalDate
- @JsonFormat -> @DateTimeFormat으로 변환
없음
Resolves #238

fix: 예약 생성 요청 시 LocalDateTime을 LocalDate로 받도록 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/CouponStatus.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/domain/CouponEventTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/domain/CouponStatusTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/reservation/domain/ReservationStatusTest.java

Accepted 상태에서 Cancel이 가능하도록 변경했습니다.
- CouponStatus 변경 사항
- 기존 : Requested 일 경우 Cancel 가능
- 변경 후 : Requested 혹은 Accepted 일 경우 Cancel 가능
- CouponEvent 변경 사항
- 기존 : Receiver만 Cancel 가능
- 변경 후 : Receiver 혹은 Sender 일 경우 Cancel 가능
- ReservationStatus는 변경 사항이 없었습니다.
- IN_PROGRESS는 쿠폰의 REQUESTED, ACCEPTED 를 품고 있어서 원래 CANCEL이 가능했습니다.
- ReservationStatus 와 CouponStatus가 동일한 역할을 하고 있습니다.
- 추후 CouponStatus를 삭제하고 ReservationStatus를 활용하면, 현재 저희가 그리는 쿠폰 로직을 동일하게 수행할 수 있을 것 같습니다. 
- CouponEvent를 보낼 수 있는 권한 확인이 필요한지 고민해볼 필요가 있을 것 같습니다.
- refactor라고 생각했는데, issue가 feat으로 되어있어서 feat으로 올립니다.
Resolves #222

feat : 쿠폰이 ACCEPTED 상태일 때 CANCEL이 가능하도록 기능 추가

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponReservationResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/query/CouponQueryRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/query/CouponReservationData.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/dto/MyCouponsReservationResponse.java
backend/src/test/java/com/woowacourse/kkogkkog/common/fixture/dto/CouponDtoFixture.java

- sender, receiver를 query상에서 잘못 가져오던 내용을 수정했습니다.
- jpql에서 sender와 receiver를 가져오도록 수정
- memberCoupon에 ImageUrl 추가
없음
Resolves #245

fix: receiver, sender 데이터를 로그인 대상으로 가져오는 문제 수정

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@hooks/@queries/user.ts
frontend/src/@pages/history/index.tsx
frontend/src/apis/user.ts
frontend/src/mocks/handlers/user.ts

[당근마켓 레퍼런스]
- 페이지에 들어오면 모든 isRead를 true로 만든다.
- 상세 페이지에 갔다가, 돌아오는 뒤로가기 액션에는 반응하지 않는다.
- 알림 하나를 누르면, 하나의 클라이언트 isRead 상태만 변경된다.
이렇게 만드려고 노력했습니다.
/history에 들어오는 방법은 3가지입니다.
1. 헤더의 종을 눌러서 들어온다.
2. 알림함 내에서 하나의 알림을 눌러서 상세 페이지로 갔다가 뒤로 가기로 돌아온다.
3. /history url을 직접 치고 들어온다.
제가 택한 방법이 1,2번 케이스를 커버하지만, 3번은 커버하지 못 합니다. (3번의 경우, isRead 처리가 안 됩니다.)
모든 경우를 커버할 방법이 잘 떠오르지 않네요.
일단 마이너한 이슈라고 생각해서 일단락하고 PR 올립니다.
Resolves #241

feat: 알림함 기능 보완

---

backend/src/docs/asciidoc/auth.adoc
backend/src/docs/asciidoc/coupon.adoc
backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponReservationResponse.java
backend/src/test/java/com/woowacourse/kkogkkog/common/fixture/dto/CouponDtoFixture.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/documentation/CouponDocumentTest.java

- Coupon 목록을 보여주는 API에 SENDER와 RECEIVER를 추가
- 현재 PR은 추후 API를 분리하면서 제거될 내용입니다.
Resolves #253

feat: 쿠폰 대상을 Sender와 Receiver로 보내주는 기능 추가

---

backend/src/docs/asciidoc/auth.adoc
backend/src/docs/asciidoc/member.adoc
backend/src/test/java/com/woowacourse/kkogkkog/auth/documentation/AuthDocumentTest.java

- 슬랙 앱 설치 RestDocs를 작성한다.
- 단일 쿠폰 상세 조회 RestDocs를 작성한다.
-  예약 요청과 상세 조회 Request, Response Fields를 작성한다.
API 변경시 걸리적거리면 RestDocs를 삭제하고 시간 여유있을 때 작성하기를 권장한다.
Resolves #248

docs: RestDocs 동기화

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/event/PushAlarmEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java

- 봇 토큰을 가져오는데 사용되는 워크스페이스도 자동갱신되도록 수정!
- 향후 Member에서 워크스페이스 정보는 제거하고, workspaceUser를 직접 활용하도록 수정할 수 있을 듯함.

fix: 로그인시 연관된 워크스페이스 정보도 자동 갱신

---

backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Nickname.java
backend/src/test/java/com/woowacourse/kkogkkog/member/domain/NicknameTest.java

- 형용사+동물명을 활용하여 닉네임을 생성합니다.
- 처음에는 동물명, 형용사 종류를 파일에서 읽어오는 방법을 생각했는데, 굉장히 마이너한 기능에 관한 정보를 `resources`에 추가하는 것에 거부감을 느껴서 Nickname 도메인 내부에 감췄습니다. 
- 커밋하지는 않았지만, 혹시 몰라서 100000번 돌려봤습니다.
Resolves #281

feat: 회원가입시 형용사와 동물명을 활용한 닉네임을 자동 생성

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/kkogkkog/auth/application/AuthService.java
backend/src/main/java/com/woowacourse/kkogkkog/auth/application/dto/MemberUpdateResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/auth/presentation/AuthController.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/SlackClient.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/dto/MemberCreateResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/dto/MemberNicknameUpdateRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
backend/src/main/java/com/woowacourse/kkogkkog/member/domain/WorkspaceUser.java
backend/src/main/java/com/woowacourse/kkogkkog/member/presentation/MemberController.java
backend/src/main/java/com/woowacourse/kkogkkog/member/presentation/dto/MemberCreateRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/member/presentation/dto/MemberUpdateMeRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/auth/application/AuthServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/auth/documentation/AuthDocumentTest.java
backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/SlackClientTest.java
backend/src/test/java/com/woowacourse/kkogkkog/member/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/member/documentation/MemberDocumentTest.java

기존 소셜 로그인 시 서버에서 회원의 존재유무에 따라 알아서 회원가입을 시켰습니다.
변경된 구조로는
소셜 로그인 시 회원이 존재하면 jwt accessToken, isNew=false를 반환하고,
회원이 존재하지 않으면 slackAccessToken과 isNew = true 를 반환합니다.
프론트에서 리다이렉트하여 /api/sign-up으로 slackAccessToken과 닉네임을 전달해주면 회원가입에 성공합니다.
Resolves #307

feat: 소셜 로그인과 회원 가입을 분리

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/reservation/application/ReservationService.java
backend/src/main/resources/db/migration/V2.0__move_meeting_date.sql

- 현재 진행 중인 리팩토링 작업이 끝나면 reservation 테이블의 meeting_date 컬럼은 coupon 테이블로 이전되어야 합니다.
- DB 마이그레이션 작업과 그에 따른 트러블슈팅을 리팩토링 작업과 분리시키기 위해 **현재 API를 그대로 사용하는 상태로 DB 마이그레이션 작업을 단계적으로 수행**하고자 합니다.
- coupon 테이블에 meeting_date 추가
- reservation 데이터가 생겨나거나 제거되면 coupon_id에 대응되는 coupon 데이터의 meeting_date 값 수정. 두 테이블의 meeting_date 데이터를 동기화시킨다.
기존 API를 그대로 사용하므로 해당 PR이 머지되어도 여전히 reservation 테이블의 meeting_date 값이 사용됩니다.
무중단 DB 마이그레이션 시나리오의 2단계에 해당. (#322 )

feat: coupon 테이블에 meeting_date 추가 및 reservation과 동기화

---

frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/business/coupon.ts
frontend/src/@hooks/business/user.ts
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/history/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/@pages/profile/index.tsx

소통하면서 개발하였기에 자세한 설명은 생략합니다!!
- query 훅의 쓰임 제한하기
- 이슈 해결
Resolves #336

refactor: React-Query 쿼리 2차 리팩터링 (query 훅의 쓰임 제한하기, 필드 유틸 함수화, 이슈 해결)

---

frontend/package.json

- build:env 환경에서 webpack mode는 production을 가리키고, api.env는 development 를 가리킵니다.
api.env가 형성되는 조건을 찾아보았습니다.
[api.env](https://babeljs.io/docs/en/config-files#apienv)는 바벨의 envName에 따라 형성됩니다. 
[envName](https://babeljs.io/docs/en/options#envname) 은 `Default: process.env.BABEL_ENV || process.env.NODE_ENV || "development"` 입니다. 
간단하게 scripts 명령어에 BABEL_ENV를 추가해줘서 해결했습니다.
Resolves #343

chore: dev build 명령어에 BABEL_ENV 추가

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/exception/WoowacoursePostMessageRequestFailedException.java
backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClientTest.java

- 환경변수 경로 설정
- 예외 발생시 로그가 error 레벨로 찍히는 문제 발견하여 요청 Webclient 재설정
작동 확인 완료하였습니다. 푸시 알림 자체는 보내지니 woowacourse일 때 잘 가는지 QA 하면 됩니다.

hotfix: woowacourse 슬랙 푸시 알림이 전송되지 않는 문제

---

frontend/src/@components/@shared/ErrorBoundary.tsx
frontend/src/@components/@shared/ErrorFallback/index.tsx
frontend/src/@components/@shared/ErrorFallback/style.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/@pages/landing/style.tsx
frontend/src/Router.tsx

- ErrorFallback 페이지 스타일링
- ErrorBoundary 우선순위 조정을 위한 리팩터링 (401 > get)
- PrivateRoute의 fallback을 Login으로 수정. 401 에러가 뜬다면, 바로 로그인으로 보내주는 것이 사용성을 증대시킨다고 생각했습니다.
Resolves #358

feat: ErrorFallback 스타일링, 에러 바운더리 리팩터링

---

frontend/src/@components/@shared/PrevPathMemoization/index.tsx
frontend/src/@pages/404/style.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/history/index.tsx
frontend/src/@pages/main/index.tsx
frontend/src/@pages/main/style.tsx
frontend/src/storage/session/index.ts

- 세션 스토리지를 활용하여 쿠폰 리스트 페이지의 필터링을 기억하도록 했습니다.
- 세션 스토로지에서 중복 코드가 발생하여 class로 분리했고, 사용처를 제한하기 위해 도메인별 getter, setter를 만들어서 export 합니다.
라이브러리에서 Theme 같은 타입을 불러올 때 타입에러가 발생합니다. 이때 import type으로 선언하면 에러가 발생하지 않습니다.
Resolves #354

feat: 쿠폰 리스트 페이지의 필터링을 기억한다.

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepositoryTest.java

Repository에서 Dto를 반환하고 있던 로직을 수정했습니다.
SpringDataJpa에서 Dto로 바로 매핑해주고 있어서 로직상 문제는 없었지만, 의존성을 분리하기 위해서 수정합니다.

fix: 보내거나 받은 쿠폰을 상태별로 전체 조회할 때 Coupon을 반환하도록 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/SlackClient.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/BotTokenResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/PostSlackMessageResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/SlackUserTokenResponse.java

- 슬랙 OAuth Response 구현
- 슬랙 알림 Response 구현
- SlackClient [PARAMETERIZED_TYPE_REFERENCE 제거](https://github.com/woowacourse-teams/2022-kkogkkog/pull/386/commits/77b514a011e6ef709d6766c6f11b511ecdf7e86e)
아서가 구글 소셜 로그인 구현 중 슬랙 클라이언트 변경을 요청하여 작업하였습니다. 
정적 Map으로 응답을 받아오던 부분을 제거하고 각각 해당하는 객체로 받아오도록 수정하였습니다. 
requestAccessToken 부분을 String 대신 Response Dto로 바꾸는 것도 제안하여 시도해봤는데 
관련 테스트의 변경과 accessToken 하나만 필요한 상황에서 현재 불 필요한 작업이라 판단하여 적용하지 않았습니다.
장기적으로 기존 구현된 SlackClient를 완전히 바꿔 구현 하는걸로 계획하고 있습니다.

refactor: 슬랙 외부 라이브러리 응답 Response 객체들 구현

---

frontend/src/@hooks/@queries/user.ts
frontend/src/types/react-query.d.ts

현재 React Query 버전에서는 개선된 setQueryData의 타이핑 영역을 선언 병합을 통해 수정합니다. (`setQueryData`의 `Updater` 함수는 쿼리 데이터를 갱신할 수도 있고 갱신하지 않을 수도 있습니다. 고로 `Input`의 타입과 `Output`의 타입은 동일해야합니다.
[@beta 버젼에는 배포가 됨 - 풀리퀘 링크](https://github.com/TanStack/query/pull/3615)
Resolves #399

refactor: QueryClient.setQueryData의 Typing Issue 해결

---

backend/src/main/java/com/woowacourse/kkogkkog/common/config/InterceptorConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/exception/CouponNotAccessibleException.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/domain/CouponTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponDocumentTest.java

- 쿠폰 상세 조회 인터셉터를 등록한다.
- 받는 사람과 보낸 사람이 아니면 쿠폰 정보를 조회하지 않고 403 Forbbiden 상태 코드를 반환한다.
없음
Resolves #388

feat: 쿠폰 상세 조회를 받는 사람 또는 보낸 사람만 조회할 수 있게 변경

---

frontend/src/@hooks/ui/coupon/useCouponPartner.ts
frontend/src/types/react-query.d.ts

- QueryClient를 interface로 작성해서, new QueryClient로 생성할 때 오류가 발생했습니다. 그래서 class로 바꾸어줬습니다. class 타입도 선언 병합 되는 것 같네요.
- 함수 오버로딩은 <오버로드 시그니처>, <구현 시그니처> 를 가집니다. 구현 시그니처는 오버로드 시그니처를 포함하는 타입이어야 합니다. 그래서 보통 any나 unknown으로 선언된 것들을 많이 보았는데요. 어떤 차이일지는 모르겠으나, 일단 가장 좁게 선언해두는 것이 좋을 것 같습니다.
```typescript
function add(a: string, b?: string, c?: string): string; // (1) overload signature
function add(a: number, b?: number, c?: number): number; // (2) overload signature
function add(a: any, b?: any, c?: any): any { // (3) implementation signature
if (b) {
if (c) {
return a + b + c;
}
return a + b;
}
return a;
};
```
Resolves #410

refactor: QueryClient 선언 병합 수정 및 useCouponPartner 함수 오버로드 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/CouponServiceTest.java

- 예약시간이 null인 경우에 대한 조건 추가로직에서 or 조건에 ()를 추가
- 이전 PR에서 조건은 추가했지만, 제대로 쿼리가 작동하지 않는 문제가 있었음
- 원인은 OR절에 () 가 생략되어서 발생한 문제
없음
Resolves #418

fix: 예약시간이 null인 경우에 대한 조건 추가

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/dto/MemberHistoryResponse.java

CouponDetailResponse에서는 enum 값을 반환하는데,
Coupon 목록으로 조회할 때는 DisplayName을 반환하고 있어서 수정합니다.
커피 -> COFFEE
추가로)
MemberHistoryResponse 반환 시 LocalDateTime이 다른 이슈가 있어서 같이 처리했습니다.
@JsonFormat이 필수인지 알았는데 스프링부트에서 디폴트로 LocalDateTime을 처리하도록 설정을 해놔서 생략해도 되더라구요.
이렇게 "2022-10-07T15:24:16.142161"

fix: CouponResponse와 MemberHistoryResponse Dto의 형식 변경

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponHistoryResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/exception/CouponNotFoundException.java

CouponNotFoundException이 500을 던지는 문제 해결
몇개 Exception이 RuntimeException을 상속받고 있는 것 같은데 내일까지 찾아보고 머지합시다.
추가 사항1.
CouponHistoryResponse에서 시간 반환 타입을 변경했습니다.
기존에 년월일 과 시분초 사이에 T가 없었는데 생성합니다.

fix: CouponNotFoundException 상속 변경, CouponHistoryResponse 시간 형태 변경

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/kkogkkog/auth/application/AuthService.java
backend/src/main/java/com/woowacourse/kkogkkog/auth/presentation/AuthController.java
backend/src/main/java/com/woowacourse/kkogkkog/auth/presentation/AuthV2Controller.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/GoogleClient.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/GoogleUserDto.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
backend/src/main/resources/application.yml
backend/src/main/resources/db/migration/V2.3__make_user_id_nullable.sql
backend/src/test/java/com/woowacourse/kkogkkog/auth/application/AuthServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/AuthDocumentTest.java
backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/GoogleClientTest.java

구글로 로그인했을 경우 2가지 경우가 있습니다.
1. 기존에 가입된 구글 or 슬랙 회원이 있는 경우
- member의 Id 값을 받아와서 토큰으로 만들어 반환한다.
2. 신규 회원인 경우
- accessToken과 isNew=true를 반환한다.
- 닉네임과 accessToken을 받아 signUp/google로 요청이 온다.
- 새로운 member를 생성한다(userId, workSpaceId는 null 이다.)
- member의 Id값을 받아와서 토큰으로 만들어 반환한다.
회원가입된 회원이 구글로 로그인하는 경우 일어나는 일은 조회 후 memberId를 읽어오는 과정만 있습니다.
문제가 될 수도 있다고 판단된 부분은 구글로 회원가입한 사용자가 다시 Slack으로 로그인 하는 경우입니다.
<구글로 회원가입한 사용자가 Slack으로 로그인하는 Flow>
1. SlackUserInfo에서 중복되는 이메일이 존재하므로 memberService의 update를 실행합니다.
2. workspaceUserRepository에는 userId와 동일한 회원이 존재하지 않습니다.
3. memberRepository에 findByEmail을 하면 구글로 가입했던 Member가 반환됩니다.
4. integrateNewWorkSpaceUser 메서드에서 현재 로그인한 Slack 계정을 기반으로 userId, imageUrl, workspace를 받아옵니다.
위 flow대로 흘러가면 문제가 없다고 판단되어서 우선 제출합니다. 혹시 이상한점 있으면 커멘트로 남겨주세요.
merge된 이후 pushAlarm 부분도 고려해보겠습니다. …

feat: 구글로 로그인했을 경우 기존 회원과 통합할 수 있도록 구현

---

backend/src/main/java/com/woowacourse/kkogkkog/KkogKkogApplication.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/AcceptedCouponResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/dto/AcceptedCouponsResponse.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepositoryTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponDocumentTest.java
backend/src/test/java/com/woowacourse/kkogkkog/support/fixture/domain/CouponFixture.java

- REQUESTED 상태의 쿠폰이 같이 조회되는 문제 해결
- repository에 요청을 보낼 때 상태도 비교하도록 수정
- 약속 날짜 당일에 쿠폰이 보이지 않는 문제 해결
- LocalDateTime.now() -> LocalDate.now().atStartOfDay() 비교하는 시간 수정
Meeting으로 있었던 메서드와 Dto를 AcceptedCoupon으로 변경했습니다.
`CouponRepository.findAllByMemberAndCouponStatusOrderByMeetingDate()` 메서드 명이 너무 길어서 개선이 필요해 보입니다.
CouponFixture를 개선해야할 필요가 있습니다.
Resolves #449

fix: 약속이 확정된 쿠폰이 정상적으로 조회되지 않는 문제 해결

---

frontend/src/@components/@shared/ErrorBoundary.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/style.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponListSection/ExpiredCouponListSection/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponListSection/RegisteredCouponListSection/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponListSection/UnregisteredCouponListSection/index.tsx
frontend/src/@hooks/@queries/unregistered-coupon.ts
frontend/src/@hooks/business/unregistered-coupon.ts
frontend/src/@hooks/ui/user/useAuthenticateForm.ts
frontend/src/@pages/main/index.tsx
frontend/src/@pages/profile/login/index.tsx
frontend/src/@pages/unregistered-coupon-list/index.tsx
frontend/src/@pages/unregistered-coupon-register/CouponCodePage.tsx
frontend/src/@pages/unregistered-coupon-register/ExpiredRegisteredCouponPage/index.tsx
frontend/src/@pages/unregistered-coupon-register/ExpiredRegisteredCouponPage/style.tsx
frontend/src/@pages/unregistered-coupon-register/IssuedRegisteredCouponPage/index.tsx
frontend/src/@pages/unregistered-coupon-register/IssuedRegisteredCouponPage/style.tsx
frontend/src/@pages/unregistered-coupon-register/RegisteredRegisteredCouponPage/index.tsx
frontend/src/@pages/unregistered-coupon-register/RegisteredRegisteredCouponPage/style.tsx
frontend/src/@pages/unregistered-coupon-register/UnregisteredCouponCodeProxyPage.tsx
frontend/src/@pages/unregistered-coupon-register/index.tsx
frontend/src/Router.tsx
frontend/src/apis/unregistered-coupon.ts
frontend/src/mocks/fixtures/unregistered-coupon.ts
frontend/src/mocks/handlers/unregistered-coupon.ts
frontend/src/storage/session/index.ts
frontend/src/types/unregistered-coupon/client.ts
frontend/src/types/unregistered-coupon/remote.ts

- 미등록 페이지 쿠폰 등록 과정 구현
- 아직 등록되지 않은 미등록 쿠폰 페이지
- 등록 완료된 미등록 쿠폰 페이지
- 기간이 만료된 미등록 쿠폰 페이지
- 쿠폰을 등록하려 할 때 로그인 되어있지 않으면, 로그인 페이지로 라우팅 합니다. 이때 sessionStorage에 couponCode를 저장해두어, 인증 완료 후 메인페이지로 돌아왔을 때 쿠폰 등록 페이지로 돌아갈 수 있도록 유도합니다.
에러바운더리 코드 아주 조금 수정했습니다. AxiosError의 response.data에 message를 담고있는지 확인하기 위해 CustomAxiosError를 만들어서 내로잉 하고 있었습니다. 그러다보니 CustomAxiosError가 아닌 AxiosError가 get 메서드일 때, 에러가 잘 포착되지 않고, 계속 children을 보여주며 에러가 반복되어 앱이 터졌습니다. 그래서 CustomAxiosError 내로잉을 제거했습니다.
Resolves #448

feat: 미등록 쿠폰 등록 과정 구현

---

frontend/src/@components/@shared/DownCount/index.tsx
frontend/src/@components/@shared/Input/index.tsx
frontend/src/@components/@shared/UpCount/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponExpiredTime/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponExpiredTime/style.tsx
frontend/src/@hooks/ui/unregistered-coupon/useUnregisteredForm.ts
frontend/src/@pages/unregistered-coupon-detail/index.tsx
frontend/src/@pages/unregistered-coupon-detail/style.tsx
frontend/src/constants/unregisteredCoupon.ts
frontend/src/mocks/fixtures/unregistered-coupon.ts
frontend/src/types/unregistered-coupon/remote.ts
frontend/src/utils/animation.ts
frontend/src/utils/time.ts

미등록 쿠폰 등록 페이지는 사용자의 쿠폰 등록 및 회원가입을 유도해야합니다. 이에 맞게 조금은 심미적인 UI를 디자인하고자 논의되었었고, 이에 맞게 `UI` 컴포넌트를 개발하였습니다. 
- `requestAnimationFrame`을 활용하여 줄어드는 시간 데이터를 렌더링하였습니다.
- 도메인에 귀속된 컴포넌트로 개발하였습니다.
- 현재 사용되는 곳이 `UnregisteredCoupon` 영역 밖에 없다.
- 다른 도메인에서 사용될 까? 의문이다. `YAGNI` 하지 않는다 👻
- 처음 렌더링 시 일, 시, 분 에 해당하는 숫자들이 카운트 업 되는 애니메이션을 트리거하는 컴포넌트를 개발하였습니다.
- `requestAnimationFrame` 을 활용하였습니다.
Resolves #462

feat: 미등록 쿠폰 등록 페이지에서 보일 시간 컴포넌트를 개발한다.

---

frontend/src/@components/@shared/ErrorFallback/index.tsx
frontend/src/@components/@shared/Header/index.tsx
frontend/src/@components/@shared/PageTemplate/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/main/index.tsx

기존의 PageTemplate은 페이지 단위로 개발되었습니다. 이러다보니 다른 페이지에서 사용하고자 할 때 의미가 모호해지는 경향이 있어 네이밍과 동작을 조금 수정하였습니다. 또한 쿠폰 상세 페이지에서도 헤더를 사용하기 위해 `PageTemplate, Header` 컴포넌트를 일부 수정합니다.
- `PageTemplate` 수정
- `Header` 수정
Resolves #464

refactor: Header 및 PageTemplate 컴포넌트 개선작업

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/domain/WoowacourseUserRepositoryImpl.java

통합 알림봇에서 userId만 있고 email이 null인 경우 NPE가 터지는 문제 해결했습니다.
코드가 지저분합니다..ㅠㅠ
Resolves #없음

fix: 통합 알림봇에서 email이 null로 오는 경우 NPE 발생하는 문제 해결

---

backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java

프록시 객체 null 확인 코드에서 문제 발생 추정
- member의 userId를 비교하게 수정
- 이슈
Resolves #493

fix: 구글로만 회원가입한 유저 나의 정보 조회 NPE 발생

---

frontend/src/@components/@shared/Modal/index.tsx
frontend/src/@components/@shared/SelectInput/index.tsx
frontend/src/@components/@shared/SelectInput/style.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/coupon/CouponCreateForm/style.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@components/user/UserSearchForm/style.tsx
frontend/src/@components/user/UserSearchModal/index.tsx
frontend/src/@components/user/UserSearchModal/style.tsx

- 키보드만으로 쿠폰 생성을 가능하게 한다.
Resolves #487

feat: 몸이 불편한 사용자도 키보드만으로 쿠폰 생성을 할 수 있다.

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@components/@shared/ListFilter/index.tsx
frontend/src/@components/@shared/ListFilter/style.tsx
frontend/src/@components/@shared/SelectInput/style.tsx
frontend/src/@components/@shared/ToastProvider/index.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/coupon/CouponItem/big.style.tsx
frontend/src/@components/coupon/CouponItem/big.tsx
frontend/src/@components/coupon/CouponItem/small.style.tsx
frontend/src/@components/coupon/CouponItem/small.tsx
frontend/src/@components/coupon/CouponList/vertical.style.tsx
frontend/src/@components/reservation/ReservationItem/index.tsx
frontend/src/@components/reservation/ReservationItem/style.tsx
frontend/src/@components/reservation/ReservationList/style.tsx
frontend/src/@components/reservation/ReservationSection/index.tsx
frontend/src/@components/reservation/ReservationSection/style.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponCreateForm/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/index.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/main/index.tsx
frontend/src/@pages/main/style.tsx
frontend/src/styles/globalStyle.ts
frontend/src/types/coupon/client.ts

- main page의 시맨틱 tag를 준수했습니다. 
- coupon list page의 시맨틱 태그를 준수했습니다.
- THUMBNAIL에 alt를 추가했습니다.
- Toast를 screen reader가 읽을 수 있도록 설정했습니다.
- Big, Small CouponItem에 @emotion의 as를 통해 동적으로 tag를 할당했습니다.
Resolves #489

feat: 쿠폰 리스트 페이지, 메인 페이지, 토스트의 웹 접근성 고려

---

frontend/src/@components/@shared/Header/index.tsx

모바일 브라우저, 데스크탑 브라우저는 모두 뒤로가기 기능을 제공합니다. 우리 서비스에서 또 제공할 필요는 없다고 생각합니다. 따라서 탈출 루트를 `Main`으로 변경합니다.
- 헤더의 뒤로가기 버튼, 로직을 제거하고 홈 버튼을 추가한다.
Resolves #466

feat: 사이트 내에 뒤로가기 버튼은 필요하지 않다.

---

frontend/src/@hooks/@queries/unregistered-coupon.ts
frontend/src/@hooks/business/unregistered-coupon.ts
frontend/src/@pages/unregistered-coupon-detail/index.tsx
frontend/src/@pages/unregistered-coupon-detail/style.tsx
frontend/src/@pages/unregistered-coupon-list/index.tsx
frontend/src/@pages/unregistered-coupon-register/IssuedRegisteredCouponPage/index.tsx
frontend/src/apis/unregistered-coupon.ts
frontend/src/mocks/fixtures/unregistered-coupon.ts
frontend/src/mocks/handlers/unregistered-coupon.ts

- 미동록 쿠폰 삭제 기능을 추가한다.
- Ajax Request 요청을 보내는 함수 개발
- useMutation 기반의 커스텀 훅 제작
- 비즈니스 로직 개발
- `mock API` 개발
- mocked API 를 개발합니다.
- `endpoint` 수정 사항 반영
- `/coupons/unregistered` -> `/lazy-coupons` 로 변경합니다.
- `IssuedUnregisteredCouponPage`의 프로미스를 핸들링하여 오류를 수정합니다.
- `mutateAsync`는 Promise를 반환합니다. 따라서 비동기 동작을 제어하고 싶다면 `async await` 키워드를 작성하거나, `then`이나 `catch`절에서 제어 이후의 작업을 기술해주어야합니다. 이전에는 그것이 제대로 되어 있지 않았기에 수정합니다.
Resolves #502

feat: 미등록 쿠폰 삭제 기능 추가 (Endpoint 수정 사항 반영)

---

frontend/src/@components/coupon/CouponStatus/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponListSection/ExpiredCouponListSection/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponListSection/RegisteredCouponListSection/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponListSection/UnregisteredCouponListSection/index.tsx
frontend/src/@hooks/ui/unregistered-coupon/useUnregisteredForm.ts
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/unregistered-coupon-list/create/index.tsx
frontend/src/@pages/unregistered-coupon-list/index.tsx
frontend/src/mocks/fixtures/unregistered-coupon.ts
frontend/src/mocks/handlers/unregistered-coupon.ts
frontend/src/types/unregistered-coupon/client.ts
frontend/src/types/unregistered-coupon/remote.ts

- 미등록 쿠폰 생성 이 후 라우팅 로직을 수정
- 하나의 쿠폰을 생성하면 디테일, 복수 개의 쿠폰을 생성하면 리스트 페이지로 라우팅 된다.
- 생성 폼에서 `Preview` 컴포넌트가 보여진다
- 미리 만들 쿠폰에 대한 뷰 정보를 제공한다.
- `Preview` 컴포넌트로 작성
- 현재 이벤트 페이지에서 사용되는 컴포넌트는 `Preview, Original`과는 분리된 컴포넌트로 작성한다.
- CreateUnregisteredCoupon Mock API를 개발한다.
- UnregisteredCoupon Type 구조 개선
- 쿠폰 도메인과 동일하게 서버 스키마 타입 구조는 클라이언트 타입 기반으로 설계되어야 합니다.
- 클라이언트의 컴포넌트 역시 클라이언트 타입 기반으로 작성되어야 합니다. 
- 서버의 반환 타입에 클라이언트 데이터 타입이 의존하지 않도록 구분하여 설계합니다.
- 서버의 반환 타입은 클라이언트 데이터 타입에 의존합니다. 
Resolves #505
Resolves #504

feat: 미등록 쿠폰 생성 이 후 라우팅 로직을 수정 & `UnregisteredCoupon.Preview` 컴포넌트 & UnregisteredCoupon Type 구조 개선

---

frontend/src/@components/coupon/CouponStatus/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponExpiredTime/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/index.tsx
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/unregistered-coupon.ts
frontend/src/@hooks/business/unregistered-coupon.ts
frontend/src/@pages/unregistered-coupon-list/index.tsx
frontend/src/@pages/unregistered-coupon-list/style.tsx
frontend/src/@pages/unregistered-coupon-register/IssuedRegisteredCouponPage/index.tsx
frontend/src/storage/session/index.ts

- 미등록 쿠폰 필터링 초기값 에러 해결
- 쿠폰 코드 페이지에 발급자도 들어갈 수는 있지만, 요청을 불가능하게 만든다. 자신이 발급한 쿠폰이 상대방에게 어떻게 보여지는지 확인할 필요가 있다고 생각해서 페이지 진입 자체를 막지는 않았습니다.
- 미등록 쿠폰 리스트에서 생성 페이지로 가는 + 버튼 구현
- 미등록 쿠폰을 등록했을 때, coupon 도메인의 key도 invalidate 시키기
- 처음으로 리액트 쿼리 다른 도메인의 key를 invalidate 시켜야하는 상황이 왔습니다. key 를 보관하는 파일을 따로 만들어서 export 처리해야할 것 같습니다. 더 이상 은닉으로 할 수 없다고 생각했습니다. 일단 구조를 바꾸지 않고, 상수 값 그대로 넣었습니다. 이후에 한번에 변경시키는 작업을 진행해야겠습니다.
- 쿠폰 등록 이후, 성공 액션 과 누가 이미 쿠폰을 등록했을때 등록 요청을 보냈을 때의 에러처리가 되고 있지 않았습니다. 근데 코드단에서 보면 되어야할 것 같은데, 왜 안되는지... dev에서 테스트해보면서 확인해보고, 다른 PR 올리든가 하겠습니다.
Resolves #이슈번호

feat: 미등록 쿠폰 조회 및 등록 기능 개선

---

frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/index.tsx
frontend/src/@pages/unregistered-coupon-register/index.tsx
frontend/src/mocks/fixtures/unregistered-coupon.ts
frontend/src/mocks/handlers/unregistered-coupon.ts
frontend/src/types/unregistered-coupon/client.ts

위를 보시면 `FetchUnregisteredCouponByStatus`의 응답 스키마가 기존과 달라졌음을 알 수 있습니다. 이에 맞게 코드를 수정합니다.
- 구현한 기능
- UnregisteredCoupon의 타입을 수정한다.
- UnregisteredCoupon의 unregisteredCouponStatus 필드를 참조하는 코드를 수정한다.
Resolves #513

fix: unregisteredCouponStatus -> lazyCouponStatus로 필드명, 타입 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/lazycoupon/application/LazyCouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/lazycoupon/domain/repository/CouponLazyCouponRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/lazycoupon/domain/repository/LazyCouponRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/lazycoupon/application/LazyCouponServiceTest.java

- 미등록 쿠폰 아이디 기반 단일 조회를 LazyCoupon의 아이디로 조회하게 변경
- 연결엔티티 조회 레포지토리 이름 변경
- ISSUE
Resolves #514

fix: 미등록 쿠폰 아이디 기반 단일 조회를 LazyCoupon의 아이디로 조회

---

frontend/src/@pages/main/index.tsx
frontend/src/@pages/unregistered-coupon-list/index.tsx

- onClickRegisteredCouponItem은 디테일 페이지로 라우팅을 트리거한다.
- 거절 페이지로 라우팅이 되고 있었으나, **보낸 쿠폰이면서** **대기중인** 쿠폰은 거절 페이지에 들어갈 수 없음. 방어로직이 되어있어 라우팅이 자꾸 뒤로 오던 현상 해결
거절 페이지로 라우팅이 되고 있었으나, **보낸 쿠폰이면서** **대기중인** 쿠폰은 거절 페이지에 들어갈 수 없음. 방어로직이 되어있어 라우팅이 자꾸 뒤로 오던 현상 해결
Resolves #518

fix: onClickRegisteredCouponItem은 디테일 페이지로 라우팅을 트리거한다.

---

frontend/src/@components/@shared/ErrorFallback/index.tsx
frontend/src/@components/@shared/ErrorFallback/style.tsx

- 헤더 제거 및 메인으로 이동하는 버튼 구현
현재 에러바운더리의 FallBackUI에서 홈 버튼을 눌러 홈 화면으로 빠져나갈려고 시도하면 라우팅은 진행되나, 페이지 렌더링이 새롭게 진행되지는 않습니다. => `error`를 갱신하지 않는 이상 리렌더링 되지 않기 때문인데, 메인으로 가기 버튼을 추가하여 해결하였습니다. (메인으로 이동되며, 클릭 시 에러 상태가 갱신)
Resolves #516

fix: 에러 바운더리 이슈 해결

---

backend/src/main/resources/application.yml

톰캣 Thread 최대 갯수와 Hikari Connection Pool의 최대 개수를 설정한다.
Tomcat 관련 설정:
```
maxThread 200 -> 10
maxConnections 8192 -> 8192
acceptCount 100 -> 10
```
HikariConnectionPool 설정:
```
maxConnections 10 -> 10
connectionTimeOut 30000ms -> 3000ms
```
노션 문서 백엔드 항목에 부하테스트 결과물과 왜 설정했는지 정리되어있습니다.
추가로 HikariCP에 connectionTimeOut 부분을 수정했는데 기본값 30초에서 3초로 줄였습니다.
해당 설정은 ConnectionPool에 모든 Connection이 사용중일 때, Connection 요청이 들어오면 대기하는 시간입니다.
사용자 입장에서 30초동안 응답이 없는 것보다는, 빠르게 에러 응답을 보내는 것이 적절하다고 판단하여 수정했습니다.
[Tomcat 관련 설정](https://kkogkkog.notion.site/1-e2eb8076a5d344c4952b4264db0d245b)
[HikariCP 관련 설정](https://kkogkkog.notion.site/e06f3189f01a462aa523d3692fabfc2d)

chore: tomcat과 hikariCP 설정

---

frontend/src/mocks/fixtures/unregistered-coupon.ts
frontend/src/types/coupon/client.ts
frontend/src/types/coupon/remote.ts
frontend/src/types/unregistered-coupon/client.ts
frontend/src/types/utils.ts

- Valueof, Elementof 타입 구분하기
- 기존에 배열의 요소를 union으로 바꾸는 타입을 Valueof라고 정의해놓았습니다. 이는 Elementof 라는 이름이 더 적절할 것 같습니다.
- keyof가 객체의 key 의 타입을 union으로 바꾸는 것이라고 하면, Valueof는 객체의 value 타입을 union으로 바꾸는 것으로 정의합니다. 이를 정의해놓았습니다.
- CouponType을 구별된 유니온으로 정의하여, couponStatus를 내로잉하면, meetingDate가 적절히 추론되도록 하였습니다.
우리가 client 타입을 정의할 때 배열을 as const로 정의하고, Elementof 방식으로 union으로 만들어 타입을 사용했습니다 근데 지금보니 이게 좀 사용성이 떨어지는 것 같습니다. enum과 같이 값으로도, 타입으로도 사용되는 상황을 바라는데, 배열로 정의해버리면 인덱스로밖에 접근할 수 없어 enum처럼 값을 찾아가기는 힘들 것 같습니다.
아직 그런 코드가 있진 않습니다!
Resolves #532

feat: Coupon 타입을 구별된 유니온으로 정의하여 couponStatus로 meetingDate 가드할 수 있도록 한다.

---

README.md

- README의 인프라 구조를 현재 구조에 맞게 수정합니다.
- [수정된 README](https://github.com/woowacourse-teams/2022-kkogkkog/tree/docs/fix-readme-infra) 참고
- 외부에 이전 인프라 구조 그림 보여주고 싶으면 이 [이 사이트 링크](https://sites.google.com/woowahan.com/woowacourse-demo-4th/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/%EA%BC%AD%EA%BC%AD/%EC%82%AC%EC%9A%A9%EA%B8%B0%EC%88%A0)를 보여주면 될 것 같습니다.

docs: README의 인프라 구조 수정
