woowacourse-teams/2022-kkogkkog

backend/src/main/java/com/woowacourse/kkogkkog/KkogKkogApplication.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponsResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/config/WebConfig.java
backend/src/test/java/com/woowacourse/kkogkkog/KkogKkogApplicationTests.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/support/DatabaseCleaner.java

- CORS 설정 추가
- 간단한 코드 스타일링: 줄 추가 및 제거 
다른 PR이 아직 없는 상태라 컨플릭이 뜰 것 같지 않아 간단한 코드 청소를 수행했습니다.
Resolves #29

chore: CORS 설정 추가

---

frontend/src/@components/@shared/PageTemplate/index.tsx
frontend/src/@pages/login/index.tsx
frontend/src/@pages/signup/index.tsx
frontend/src/Router.tsx
frontend/src/styles/globalStyle.ts

- 구현한 기능
- Login UI 구현했습니다. 
- 회원가입 페이지 미리 만들어 두었고, 라우팅 걸어뒀습니다.
- globalStyle 에서 button에 border: 0 넣어두었습니다. 버튼 기본 border가 1px solid black인 것 같은데, 이것을 쓸일이 없을 것 같아서 설정했습니다.
Resolves #
(API 연동 PR에서 Resolves 하겠습니다.)

feat: Login UI 구현

---

frontend/src/@components/@shared/Input/index.tsx
frontend/src/@components/@shared/Input/style.tsx
frontend/src/@pages/login/index.tsx

Input Component 두 가지 형태로 분리
Resolves #47

refactor: Input Component 두 가지 형태로 분리

---

frontend/src/apis/index.ts
frontend/src/apis/kkogkkog.ts
frontend/src/hooks/useAuthenticateForm.ts

회원가입 API 연동
- 구현한 기능
- mutate 사용
mutate 사용 룰 정하면 좋을것 같아요~
1. 함수명은 어떻게 짓는다
2. deconstructing 한다 / 안한다
Resolves #21

feat: 회원가입 API 연동

---

frontend/src/@components/@shared/Icon/Icons/Close.tsx
frontend/src/@components/@shared/Icon/Icons/index.tsx
frontend/src/@components/@shared/Input/style.tsx
frontend/src/@components/kkogkkog/KkogKkogCreateForm/index.tsx
frontend/src/@components/kkogkkog/KkogKkogCreateForm/style.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@components/user/UserSearchForm/style.tsx
frontend/src/@pages/kkogkkog-list/create/index.tsx
frontend/src/hooks/useModal.ts
frontend/src/styles/globalStyle.ts

UserSearchForm 개발
Resolves #49

feat: User Search UI 개발

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/application/dto/MemberResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/config/InterceptorConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java

- 로그인 했을 경우 본인의 정보를 조회하는 API 구현
#57 PR Merge 시 conflict 가능성이 있음
Resolves #58

feat: 본인 정보 조회 API 구현

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@pages/kkogkkog-list/create/index.tsx
frontend/src/@pages/profile/index.tsx
frontend/src/Router.tsx
frontend/src/apis/index.ts
frontend/src/apis/kkogkkog.ts
frontend/src/apis/user.ts
frontend/src/hooks/useAuthenticateForm.ts
frontend/src/hooks/useMe.ts
frontend/src/index.tsx
frontend/src/mocks/fixtures/users.ts
frontend/src/mocks/handlers/index.ts
frontend/src/mocks/handlers/user.ts

- 회원가입 기능 구현
- 로그인 기능 구현
- 인가 기능 구현
- 내 정보 요청 기능 구현
- 세부 작업2
Resolves #22

feat: 로그인 기능 구현

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@components/kkogkkog/KkogKkogCreateForm/index.tsx
frontend/src/@components/kkogkkog/KkogKkogItem/index.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@hooks/@common/useStatus.ts
frontend/src/@hooks/kkogkkog/useKkogKkogForm.ts
frontend/src/@hooks/kkogkkog/useKkogKkogList.ts
frontend/src/@hooks/user/useMe.ts
frontend/src/@hooks/user/useSearchUser.ts
frontend/src/@hooks/user/useUserList.ts
frontend/src/@pages/kkogkkog-list/create/index.tsx
frontend/src/@pages/kkogkkog-list/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/Router.tsx
frontend/src/index.tsx
frontend/src/mocks/fixtures/users.ts
frontend/src/mocks/handlers/kkogkkog.ts
frontend/src/types/client/kkogkkog.ts

- Coupon List UI 개선
- Coupon Create Form UI 개선
Resolves #23

feat: 멤버별 쿠폰 조회 구현 및 인증이 있는 쿠폰 생성 기능

---

frontend/src/@components/@shared/Modal/index.tsx
frontend/src/@components/@shared/Modal/style.tsx
frontend/src/@components/kkogkkog/KkogKkogModal/index.tsx
frontend/src/@components/kkogkkog/KkogKkogModal/style.tsx

- 컴포넌트 상태에 따라 띄어지는 다양한 모달을 컴포넌트화 했습니다.
컴포넌트는 buttons, title, children을 props로 받습니다.

feat: Modal.WithHeader 컴포넌트 구현

---

frontend/src/@components/@shared/ListFilter/index.tsx
frontend/src/@components/@shared/ListFilter/style.tsx
frontend/src/@components/kkogkkog/KkogKkogItem/index.tsx
frontend/src/@components/kkogkkog/KkogKkogList/index.tsx
frontend/src/@components/kkogkkog/KkogKkogList/style.ts
frontend/src/@components/kkogkkog/KkogKkogModal/index.tsx
frontend/src/@components/kkogkkog/ReceivedKkogKkog/index.tsx
frontend/src/@components/kkogkkog/ReceivedKkogKkog/style.tsx
frontend/src/@components/kkogkkog/SentKkogKkog/index.tsx
frontend/src/@components/kkogkkog/SentKkogKkog/style.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/mocks/fixtures/kkogkkogs.ts
frontend/src/mocks/handlers/kkogkkog.ts
frontend/src/styles/theme.ts

- 인증이 있는 쿠폰 조회 기능 구현
- 받은 쿠폰, 보낸 쿠폰을 구분하여 조회가 가능
- 쿠폰 상태에 따라 구분하여 조회가 가능
Resolves #23

feat: 멤버별 쿠폰 조회 구현 및 쿠폰 상태 별 조회 UI 구현

---

frontend/src/@components/kkogkkog/KkogKkogCreateForm/index.tsx
frontend/src/@components/kkogkkog/KkogKkogCreateForm/style.tsx
frontend/src/@components/kkogkkog/ReceivedKkogKkog/index.tsx
frontend/src/@components/kkogkkog/SentKkogKkog/index.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@components/user/UserSearchForm/style.tsx
frontend/src/@hooks/kkogkkog/useKkogKkogForm.ts
frontend/src/@pages/landing/index.tsx

- 선택된 유저가 Input UI에 표시된다.
-  이 UI는 클릭하는 등의 상호작용이 가능하다.
- 유저 검색 창에서의 선택 유저 UI와 Input에서의 선택 유저 UI 통일
- 쿠폰을 생성하면 랜딩 페이지의 보낸 쿠폰이면서 대기 상태인 쿠폰들이 보여진다.
Resolves #95

refactor: 쿠폰 생성 폼의 유저 선택 UI 개선

---

backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponStatus.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponStatusTest.java

- 보낸 사람(Sender)이 쿠폰 사용 요청을 거절하는 기능 구현
없음
Resolves #91

feat : 쿠폰 사용 요청 거절 API 구현

---

frontend/src/@components/@shared/Modal/index.tsx
frontend/src/@components/@shared/Modal/style.tsx
frontend/src/@components/kkogkkog/KkogKkogCreateForm/index.tsx
frontend/src/@components/kkogkkog/KkogKkogItem/index.tsx
frontend/src/@components/kkogkkog/KkogKkogList/index.tsx
frontend/src/@components/kkogkkog/KkogKkogModal/index.tsx
frontend/src/@components/kkogkkog/ReceivedKkogKkog/index.tsx
frontend/src/@components/kkogkkog/ReceivedKkogKkog/style.tsx
frontend/src/@components/kkogkkog/SentKkogKkog/index.tsx
frontend/src/@components/kkogkkog/SentKkogKkog/style.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@components/user/UserSearchModal/index.tsx
frontend/src/@hooks/kkogkkog/useChangeKkogKkogStatus.ts
frontend/src/@hooks/kkogkkog/useKkogKkogForm.ts
frontend/src/@hooks/user/useAuthenticateForm.ts
frontend/src/@hooks/user/useMe.ts
frontend/src/@hooks/user/useSearchUser.ts
frontend/src/@pages/kkogkkog-list/create/index.tsx

- 거절 기능 구현
- 모달 내려가는 애니메이션 구현
- 검색하지 않아도 유저 리스트가 보이도록 구현

feat: 2차 데모 

---

frontend/src/@pages/kkogkkog-list/index.tsx
frontend/src/types/client/kkogkkog.ts

- reduce에 제네릭 타입 추가했습니다.
Resolves #105

refactor: reduce 제네릭 타입 추가

---

backend/src/main/java/com/woowacourse/kkogkkog/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/MemberHistory.java
backend/src/main/java/com/woowacourse/kkogkkog/domain/repository/MemberHistoryRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java

쿠폰 생성에 대한 History 생성 기능 구현
쿠폰 상태 변경에 대한 History 생성 기능 구현
History 조회 기능을 구현하면서 AOP로 변경할 예정입니다.
Resolves #138

feat: 쿠폰 상태 변경에 대한 History 생성 기능 구현

---

backend/.gitignore
backend/src/main/java/com/woowacourse/kkogkkog/config/LogAspect.java
backend/src/main/java/com/woowacourse/kkogkkog/exception/GlobalControllerAdvice.java
backend/src/main/resources/console-appender.xml
backend/src/main/resources/file-all-appender.xml
backend/src/main/resources/file-error-appender.xml
backend/src/main/resources/file-info-appender.xml
backend/src/main/resources/logback-spring.xml
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java

Slf4j 구현체 중 Logback을 이용하여 구현했습니다. logback 관련 설정은 resources 에 xml 관련 파일들로 작성했습니다.
prod일 경우 file로 저장하고 3가지 파일로 구분지어집니다. 
```
1. 전체 로그를 작성하는 파일 
2. error만 작성하는 파일
3. info만 작성하는 파일
```
prod가 아닐 경우 콘솔에 출력합니다.
logLevel은 Info 와 Error만 사용했습니다. 정상적인 흐름(예상된 exception 포함)에서는 모두 Info로 기록되고 500번대 에러 혹은 예상치 못한 에러가 발생했을 시에 Error 로그가 기록되도록 구현했습니다.
LogAspect는 현재 presentation 패키지에 있는 클래스의 모든 메서드에 대해서 작동하며 request와 response를 로깅하는 구조입니다. `@AfterReturning` 과 `@AfterThrowing` 을 구분지어 성공했을 때와 예외가 발생했을 때 처리하는 로깅이 다릅니다. 
traceId를 넣어주기 위해서 MDC를 활용했습니다. 클라이언트 별로 로그를 찾을 때 유용하다고 하여 넣어봤습니다.
아래는 로깅 출력 정보와 로깅 예시입니다.
```
<INFO>
Request : Http 메서드 / Request URL / Request Params
Respnse : Http Status / JoinPoint(성공한 메서드 이름)
Exception : JoinPoint(실패한 메서드 이름) / 던져진 예외
<ERROR>
UnhandledException : 던져진 예외
```
```java …
```

feat : 로깅 기능 구현

---

frontend/.pnp.cjs
frontend/package.json
frontend/src/@components/@shared/Header/index.tsx
frontend/src/@components/coupon/CouponModal/index.tsx
frontend/src/@components/user/MockLoginFrm/index.tsx
frontend/src/@components/user/MockLoginFrm/style.tsx
frontend/src/@hooks/coupon/useChangeCouponStatus.ts
frontend/src/@pages/landing/style.tsx
frontend/src/@pages/login/index.tsx
frontend/yarn.lock

- [시맨틱 버저닝 추가](https://github.com/woowacourse-teams/2022-kkogkkog/commit/4c01c00a4d2ec11084f800fc8851fef97302ce08)
- [개발 환경에 따른 로그인 환경 분리](https://github.com/woowacourse-teams/2022-kkogkkog/commit/5b3083aa5ac87e5044d94c57032e14f1840e1a70)
- [랜딩의 쿠폰 생성 border-radius 조정](https://github.com/woowacourse-teams/2022-kkogkkog/commit/d34d1db432efff21c224b3f000718ea6a6c45cfc)
- [뒤로가기 -1 동작하지 않는 오류 해결](https://github.com/woowacourse-teams/2022-kkogkkog/commit/c20bcabf8e8137562e6c714d99fdd515b183d192)
- [쿠폰 거절 추가](https://github.com/woowacourse-teams/2022-kkogkkog/commit/773ee5fdf9921153e89ffb1976f3a5eff765aedc)
Resolves #175

feat: 1차 QA

---

frontend/src/@components/coupon/CouponModal/index.tsx

hotfix: 쿠폰 사용 요청 모달에서 완료 버튼 제거

---

.gitmodules
backend/.gitignore
backend/build.gradle
backend/src/main/resources/application.yml

- backend 민감정보 관리를 위해서 `submodule`을 설정한다.
- submodule을 설정
- prod, dev yml 등록
`Submodule` 설정 방법에 대해서 노션을 꼭 읽어주시면 감사하겠습니다. 
추가적으로 `team organization` 승인을 받아주셔야 정상적으로 사용이 가능합니다!!
Resolves #116

feat: submodule을 설정

---

backend/build.gradle

- Gradle Task 수정
- 환경별 yml gradle task 수정
- Rest Docs gradle task 수정
기존에 로컬에서도 `Rest Docs html`을 볼 수 있게 하였지만 활용성이 떨어진다 생각해서 제거했습니다!!
Resolves #193

chore: gradle task 수정

---

frontend/src/@components/@shared/PageTemplate/style.tsx
frontend/src/@components/@shared/ToastProvider/index.tsx
frontend/src/@components/@shared/ToastProvider/style.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@hooks/@common/usePreventReload.ts
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/coupon/useChangeCouponStatus.ts
frontend/src/@hooks/coupon/useCouponForm.ts
frontend/src/mocks/handlers/user.ts
frontend/src/styles/theme.ts

- 피드백 UI를 추가한다.
- 쿠폰 생성 페이지 새로고침 제한
- usePreventReload 훅 개발
Resolves #185

feat: user interaction 추가

---

frontend/src/@pages/redirect/index.tsx
frontend/src/types/remote/response.ts

- 유저는 최초 익명1234 같은 형식의 닉네임을 부여받는다. 최초 로그인이라면 Profile Edit Page로 링크된다.
Resolves #208

feat: Slack Oauth 후 닉네임 변경하기

---

frontend/src/@pages/download/index.tsx
frontend/src/@pages/login/index.tsx

- 배포 환경에 따라 slack redirect uri 구분하기

refactor: 배포 환경에 따라 slack redirect uri 구분하기

---

frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/coupon/CouponItem/big.tsx
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/coupon/useCouponForm.ts
frontend/src/@pages/coupon-list/create/index.tsx
frontend/src/mocks/fixtures/coupon.ts
frontend/src/mocks/handlers/coupon.ts
frontend/src/types/remote/request.ts

refactor: 쿠폰 생성 API 명세 변경에 따른 수정

---

frontend/src/@hooks/coupon/useChangeCouponStatus.ts
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/apis/coupon.ts
frontend/src/types/remote/request.ts

refactor: API 명세 변경에 따른 대응

---

backend/src/docs/asciidoc/member.adoc
backend/src/main/java/com/woowacourse/kkogkkog/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/presentation/MemberController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/AcceptanceContext.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/MemberControllerTest.java

- 나의 히스토리 열람 여부를 모두 True로 변경하는 기능 구현
없음
Resolves #250

feat: 나의 히스토리 전체 열람 변경 기능 구현

---

frontend/src/@components/@shared/PageTemplate/style.tsx
frontend/src/@components/coupon/CouponItem/big.tsx
frontend/src/@components/reservation/ReservationItem/style.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/coupon/useChangeCouponStatus.ts
frontend/src/@hooks/user/useEditProfileForm.ts
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/style.tsx
frontend/src/@pages/landing/style.tsx
frontend/src/@pages/profile/edit/index.tsx
frontend/src/@pages/redirect/index.tsx
frontend/src/apis/coupon.ts
frontend/src/types/remote/response.ts
frontend/src/utils/index.ts

feat: 쿠폰 상태 변경 인자로 reservationId 넣어주기

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponDetailResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/query/CouponDetailData.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/query/CouponQueryRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/common/fixture/dto/CouponDtoFixture.java

쿠폰 상세 조회시 reservationId를 같이 반환하도록 수정

fix: Coupon 상세조회에서 reservationId를 같이 반환하도록 수정

---

frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx

fix: 타이핑 긴급 대응

---

frontend/src/@hooks/coupon/useChangeCouponStatus.ts
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/types/remote/request.ts

feat: 승인 및 거절에 메시지 보내도록 수정

---

frontend/src/@pages/coupon-list/coupon-detail/style.tsx
frontend/src/utils/time.ts

- 쿠폰 Interaction Page 배경색 추가
- Date 로직 수정
Resolves #이슈번호

feat: 쿠폰 Interaction Page 배경색 추가, Date 로직 수정

---

frontend/src/@components/@shared/Icon/index.tsx
frontend/src/@components/reservation/ReservationSection/index.tsx
frontend/src/@hooks/coupon/useCouponForm.ts
frontend/src/@pages/coupon-list/coupon-detail/request/style.tsx
frontend/src/@pages/profile/index.tsx

- 쿠폰 생성 후, 상세페이지 -> 홈 뒤로가기
- 캘린더가 계속 클릭되는 현상 해결
- 프로필 페이지에서 뒤로가기 두번 눌러야하는 현상 해결
- 승인된 쿠폰 없을 때 보이는 손바닥 Icon에서 cursor 제거

feat: QA 진행 후 반영

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/query/CouponQueryRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/reservation/application/ReservationService.java
backend/src/main/java/com/woowacourse/kkogkkog/reservation/application/dto/ReservationSaveRequest.java
backend/src/main/java/com/woowacourse/kkogkkog/reservation/domain/Reservation.java
backend/src/test/java/com/woowacourse/kkogkkog/common/fixture/domain/ReservationFixture.java
backend/src/test/java/com/woowacourse/kkogkkog/core/coupon/domain/query/CouponQueryRepositoryTest.java
backend/src/test/java/com/woowacourse/kkogkkog/core/reservation/acceptance/ReservationAcceptanceTest.java

- 현재 구현된 내용과 불일치 하는 Status를 제거
- ReservationStatus 제거
- @OneToOne으로 변경
- 다시 처음부터 고민해보십다..

fix: Reservation의 상태를 제거

---

frontend/src/@components/coupon/CouponItem/big.style.tsx
frontend/src/@components/reservation/ReservationSection/index.tsx
frontend/src/@components/reservation/ReservationSection/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/style.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/mocks/fixtures/coupon.ts
frontend/src/utils/time.ts

- UX Writing 수정
- 쿠폰 Message ellepsis

feat: UX Writing 수정

---

frontend/public/index.html
frontend/src/@components/coupon/CouponItem/big.style.tsx

- title 추가
- og-graph 추가
- 사이트 keywords, description 추가
og-graph image는 상대경로로 지정할 수 없습니다.
s3에 올리면 좋겠지만, 안 되니까 깃허브 이슈에서 사진 등록해서, 그 url 이용했습니다.
Resolves #267

feat: meta tag를 추가한다.

---

frontend/src/@components/@shared/Dimmed/index.tsx
frontend/src/@components/@shared/Icon/index.tsx
frontend/src/@components/@shared/Loading/index.tsx
frontend/src/@pages/redirect/index.tsx
frontend/src/Router.tsx

- 귀신 -> 로고로 변경
- Icon 커서 문제 해결
Resolves #269

feat: 로딩 컴포넌트 수정

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@components/@shared/ToastProvider/style.tsx
frontend/src/@pages/redirect/index.tsx
frontend/src/utils/time.ts

- 뒤로가기 버튼 키움
- Toast UI 이슈 해결
- z-index로 발생한 에러 해결
- Time.ts의 로직 수정
Resolves #270

feat: toast UI 이슈 해결 및 헤더의 뒤로가기 버튼 사이즈 조절

---

frontend/src/@hooks/@common/useTokenMutation.ts
frontend/src/@hooks/@common/useTokenQuery.ts
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts

- refetch 시 token 확인하여 로그인으로 리다이렉트 시키기
Resolves #270

feat: refetch 시 token 확인하여 로그인으로 리다이렉트 시키기

---

frontend/src/@components/coupon/CouponHistoryItem/index.tsx
frontend/src/@components/coupon/CouponHistoryItem/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/style.tsx

- Description 섹션 추가
- 영문 줄바꿈 추가
- 쿠폰 히스토리 요청 액션인 경우 날짜 추가
Resolves #270

feat: Detail 페이지에 설명 섹션 추가, 쿠폰 히스토리 영문 줄바꿈-요청 날짜 추가

---

frontend/src/@hooks/@queries/user.ts
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/style.tsx
frontend/src/Router.tsx
frontend/src/index.tsx

- [getMe 제외 staleTime 제거](https://github.com/woowacourse-teams/2022-kkogkkog/commit/d1ea946eac3ca7042820cb21271692ee8ae685e9)
- 페이지에 suspense 추가
- [하단 이벤트 버튼 max-width 설정 및 가운데 정렬](https://github.com/woowacourse-teams/2022-kkogkkog/commit/b4f48548aac666cca54a1b99174bb6f6d25b243c)
Resolves #270

feat: QA 진행 후 수정

---

frontend/src/@components/@shared/LoadingProvider/index.tsx
frontend/src/@components/@shared/ToastProvider/style.tsx
frontend/src/@components/coupon/CouponHistoryItem/style.tsx
frontend/src/@hooks/@common/useLoading.ts
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/coupon/useCouponForm.ts
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/index.tsx

- Mutate 액션에 Loading 추가
- 글자 깨지는 이슈 해결
- 쿠폰 액션 이후 리스트 페이지로 라우팅
[QA 링크](https://www.notion.so/kkogkkog/8-16-1-QA-26f6b46b99af4d449651ab48d766672c)
Resolves #270

feat: Mutate 액션에 Loading 추가, 글자 깨지는 이슈 해결, 쿠폰 액션 이후 리스트 페이지로 라우팅

---

frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx

- 보낸 쿠폰의 액션이면 보낸 쿠폰 리스트로, 받은 쿠폰의 액션이면 받은 쿠폰 리스트로 이동시킨다.
Resolves #270

feat: 보낸 쿠폰의 액션이면 보낸 쿠폰 리스트로, 받은 쿠폰의 액션이면 받은 쿠폰 리스트로 이동시킨다.

---

frontend/src/@components/coupon/CouponCreateForm/style.tsx
frontend/src/@components/coupon/CouponHistoryItem/style.tsx
frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx

- Coupon Action Navigate에 replace 추가
- 필요한 곳에 stale time 추가
- 쿠폰 리스트
- 유저 히스토리
- 스타일 수정
- 글자 넘치지 않게 스타일 수정 
Resolves #270

feat: Coupon Action Navigate에 replace 추가, 필요한 곳에 stale time 추가, 스타일 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/common/config/AsyncConfig.java
backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListenerTest.java

- AsyncConfig 클래스에 비동기 설정 Bean 등록
- 푸시 알림 리스너 메서드 비동기 변경
테스트가 실패하는 경우가 있어 알림 부분 Mock.verify() 메서드에 timeout을 설정함
Resolves #286

refactor: 슬랙 알림 비동기 변경 

---

frontend/src/@components/reservation/ReservationSection/index.tsx
frontend/src/utils/time.ts

- 예약 확정 섹션 정렬 방식 수정
Resolves #270

refactor: 예약 확정 섹션 정렬 방식 수정

---

backend/build.gradle
backend/src/main/resources/application.yml
backend/src/main/resources/logback-spring.xml
backend/src/main/resources/slack-appender.xml

- Logback 설정에 SlackAppender 추가
- 슬랙 웹훅 url 환경변수 설정
Dev, Prod 모두 Error 레벨 설정
Resolves #289

chore: Error 로그가 슬랙에 전송되는 기능 구현

---

.github/workflows/ci-lighthouse.yml
frontend/.lighthouserc.js

최초에는 몇가지 고민이 있어 CI를 미룰까 했습니다.
- 측정할 페이지 선정이 어렵지 않을까? (추상적임)
- 그렇다고 모든 페이지를 측정하는게 맞을까? (개발비용이 들어감)
허나 메인 페이지를 측정 페이지로 선정하게 되어 CI를 바로 진행합니다. 메인페이지를 선정한 이유는 다음과 같습니당
1. 인증된 사용자가 가장 처음 마주하는 화면
2. 의외로 사용자에게 주는 도메인 내용이 많다. (쿠폰을 관리, 예약된 쿠폰 확인, 쿠폰 만들기 등등)
그렇기에 핵심이 되는 페이지라 생각되어 선정!
Resolves #290

feat: lighthouse CI 설정

---

README.md

[편하게보기](https://github.com/woowacourse-teams/2022-kkogkkog/blob/docs/all-read-me/README.md)
- 작성 목록
- 간판
- 서비스 소개 
- 팀원 소개
의견 공유용 PR입니다.
Resolves #293

docs: README 서비스 소개, 팀원 소개 작성

---

backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Nickname.java
backend/src/test/java/com/woowacourse/kkogkkog/member/domain/NicknameTest.java

- 닉네임 확인 정규식과 테스트를 1자 이상으로 수정한다.
전체 테스트 돌렸는데 예전이랑 다르게 느려요ㅠ
Resolves #304

feat: 닉네임 글자 수 1-6글자 변경

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/user/useAuthenticateForm.ts
frontend/src/@hooks/user/useSlackOAuth.ts
frontend/src/@pages/404/style.tsx
frontend/src/Router.tsx
frontend/src/apis/user.ts
frontend/src/styles/globalStyle.ts
frontend/src/types/remote/request.ts

feat: 스타일 이슈 해결 및 회원가입 로직 수정사항 반영

---

frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/user/useSlackOAuth.ts

- api client에 setting 되지 않아 랜딩 페이지가 비 인증 랜딩 페이지 상태로 머물러있는 이슈 해결
Resolves #316

feat: 로그인 성공 시 AccessToken를 api client에 setting

---

backend/src/test/java/com/woowacourse/kkogkkog/auth/documentation/AuthDocumentTest.java

- 회원가입 RequestBody를 MemberCreateRequest로 변경한다.
없음

docs: 회원가입 restDocs RequestBody 올바르게 변경

---

backend/src/main/resources/db/migration/V2.1__move_meeting_date.sql

- reservation 테이블과 coupon 테이블의 meeting_date 완전히 동기화
- 현재 작업 중인 도메인 리팩토링 브랜치가 머지되었을 때 별도의 DB 작업 불필요할 예정 
#322 의 3단계에 해당

feat: 기존 meeting_date 데이터 마이그레이션

---

frontend/package.json
frontend/src/@components/@shared/ErrorBoundary.tsx
frontend/src/@components/reservation/ReservationItem/index.tsx
frontend/src/@hooks/ui/coupon/useCouponForm.ts
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/history/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/Router.tsx

- Dynamic Path를 함수화한다.
Resolves #338

refactor: Dynamic Path를 함수화한다.

---

frontend/src/@components/@shared/OnlyNumberDynamicRouting/index.tsx
frontend/src/@components/@shared/SelectInput/index.tsx
frontend/src/@components/@shared/SelectInput/style.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/user/UserSearchForm/style.tsx
frontend/src/@hooks/ui/user/useEditProfileForm.ts
frontend/src/@pages/404/index.tsx
frontend/src/@pages/404/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/profile/index.tsx
frontend/src/Router.tsx
frontend/src/types/client/coupon.ts

동적 라우팅 시 들어가는 키-밸류 구조의 자료구조의 타입을 체크하는 범용적인 컴포넌트를 만들고자 하였으나, 당장 필요한게 아니라 미룹니다. 시간날 때 지금 컴포넌트(number 타입인지만 검증하는)보다 더 범용적인 함수 컴포넌트를 만들 계획입니당
Resolves #348

feat: 09-15 QA

---

frontend/src/@hooks/@queries/coupon.ts
frontend/src/@hooks/@queries/user.ts
frontend/src/apis/coupon.ts
frontend/src/apis/service.ts
frontend/src/apis/user.ts

- 간단하게 fetcher 함수 수정하고, data 하나 뗐습니다.
- AddSlackApp을 service에서 user 도메인으로 이동했습니다.
Resolves #342

refactor: fetcher 함수의 response에서 data만 추출하여 return 한다.

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@hooks/ui/coupon/useCouponForm.ts
frontend/src/@hooks/ui/user/useAuthenticateForm.ts
frontend/src/@pages/404/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/@pages/landing/style.tsx
frontend/src/@pages/main/index.tsx
frontend/src/@pages/main/style.tsx
frontend/src/@pages/profile/index.tsx
frontend/src/@pages/redirect/index.tsx
frontend/src/Router.tsx

공유하며 개발을 진행하였기에 코멘트는 간단히 남깁니다.
- 랜딩 페이지 라우팅을 구분합니다.
- 랜딩 페이지 컴포넌트 분리 (비인증, 인증)
- 라우터 수정(비인증 - /landing , 인증 - /main)
- 인증 인가 고도화
- 인증되어 있는 유저의 경우 인가 고도화
- 쿠폰 인가 고도화
Resolves #337
Resolves #325

feat: 랜딩 페이지 라우팅 구분하기 & 인증 인가 고도화

---

frontend/src/@components/coupon/CouponHistoryItem/style.tsx

- 쿠폰 히스토리 메시지 스타일 수정
Resolves #353

feat: 쿠폰 히스토리 메시지 스타일 수정

---

backend/src/main/java/com/woowacourse/kkogkkog/legacy_coupon/application/LegacyCouponService.java

레거시 코드에서 쿠폰 생성할 때 알람이 안오는 문제 해결

fix: coupon 생성시 알람이 안오는 문제 해결

---

frontend/src/@pages/coupon-list/index.tsx
frontend/src/Router.tsx

- Code Splitting, 페이지 컴포넌트를 lazy Component로 만든다.
페이지 컴포넌트의 Fallback(Skeleton)은 lazy 처리 하지 못 합니다.
Resolves #365

feat: Code Splitting, 페이지 컴포넌트를 lazy Component로 만든다.

---

backend/src/main/resources/logback-spring.xml

fix: slack-appender.xml 실행 프로파일 이름 변경

---

frontend/src/@components/@shared/ErrorBoundary.tsx

fix: ErrorBoundary에서 reset 로직 제거

---

frontend/src/@components/@shared/Header/index.tsx
frontend/src/@components/@shared/Loading/index.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/coupon/CouponCreateForm/style.tsx
frontend/src/@components/coupon/CouponHistoryItem/index.tsx
frontend/src/@components/coupon/CouponHistoryItem/style.tsx
frontend/src/@components/coupon/CouponItem/big.style.tsx
frontend/src/@components/coupon/CouponItem/big.tsx
frontend/src/@components/coupon/CouponItem/small.tsx
frontend/src/@components/coupon/CouponList/horizontal.tsx
frontend/src/@components/coupon/CouponList/vertical.tsx
frontend/src/@components/reservation/ReservationItem/index.tsx
frontend/src/@components/reservation/ReservationItem/style.tsx
frontend/src/@components/user/UserHistoryItem/index.tsx
frontend/src/@components/user/UserHistoryItem/style.tsx
frontend/src/@pages/404/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/accept/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/decline/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/style.tsx
frontend/src/@pages/download/index.tsx
frontend/src/@pages/join/index.tsx
frontend/src/@pages/landing/index.tsx
frontend/src/@pages/login/index.tsx
frontend/src/@pages/profile/edit/index.tsx
frontend/src/@pages/profile/index.tsx

- 이미지 height 명시함으로써 Layout Shift 현상 제거
Resolves #373

feat: 이미지 height 명시함으로써 Layout Shift 현상 제거

---

backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/SlackUserInfo.java

- 유저 프로필 이미지 사이즈를 변경한다.
https://api.slack.com/methods/openid.connect.userInfo
프론트 요구 사항

refactor: user profile 이미지 사이즈 변경

---

backend/src/main/resources/db/migration/V2.2__fix_workspace_id.sql

- 노션에 작성했던 오래된 버전의 DDL을 활용하여 초기 테이블 스키마를 셋업하여 prod/dev 테이블 구조와 불일치 발생함.
- 운영 서버, 개발 서버에서는 사전에 생성해놓은 제대로 된 테이블 구조를 사용하여 문제가 발견되지 않았음.
- 다만, 테스트 서버 셋업 과정에서 V1 스키마를 사용하며 문제가 발생하였으므로 현재 구조에 맞게 컬럼 타입 수정함. 
- 추가로 서브모듈 변경 내역도 반영

fix: 스키마 및 서브모듈 변경 내역 반영

---

frontend/src/types/axios.d.ts

- axios headers에 Authorization 선언 병합
Resolves #394

refactor: axios headers에 Authorization 선언 병합

---

frontend/src/@components/coupon/CouponList/horizontal.tsx
frontend/src/@components/coupon/CouponListSection/FinishedCouponListSection/index.tsx
frontend/src/@components/coupon/CouponListSection/WaitingCouponListSection/index.tsx
frontend/src/@hooks/@queries/user.ts
frontend/src/@hooks/business/coupon.ts
frontend/src/@hooks/types.ts
frontend/src/@hooks/ui/coupon/useCouponPartner.ts
frontend/src/@hooks/ui/user/useAuthenticateForm.ts
frontend/src/@hooks/ui/user/useEditProfileForm.ts
frontend/src/@pages/coupon-list/coupon-detail/index.tsx
frontend/src/utils/tobe-time.ts

상대경로는 ./ 와 ../ 일때만 사용합니다.
이외의 경우는 절대 경로를 사용합니다.
Resolves #403

refactor: 상대 경로를 절대 경로로 수정

---

backend/src/main/resources/application.yml

구글 로컬 redirectUrl 변경했습니다. 프론트에서 mock으로 사용하려고하여 변경합니다.
Resolves #이슈번호없음

refactor: 구글 로컬 redirectUrl 변경

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepository.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/ConcurrentCouponServiceTest.java

- 예약시간이 null인 경우에 대한 조건 검증을 추가
- IS NOT NULL을 통해서 먼저 예약 시간 조건에 대한 검증을 수행합니다
- NullPointException 위험성이 있어서, 시간과 관련된 속성들은 1:1로 테이블을 분리해서 설계를 고려 해보려고 합니다.
Resolves #418

fix: 예약시간이 null인 경우에 대한 조건 추가

---

frontend/src/@pages/coupon-create-select/index.tsx
frontend/src/@pages/coupon-create-select/style.tsx
frontend/src/@pages/main/index.tsx
frontend/src/@pages/unregistered-coupon-list/create/index.tsx
frontend/src/Router.tsx

쿠폰 생성 프록시 페이지를 개발하였습니다.
- 워딩은 일단 미등록 쿠폰으로 통일합니다.
- 라우팅은 대화로 토의 완료
- 디자인은 미리 진행합니다.
Resolves #424

feat: 쿠폰 선택 페이지 개발

---

frontend/src/@pages/main/index.tsx

received/sent 쿠폰을 거꾸로 설정한 에러 해결
Resolves #440

fix: received/sent 쿠폰을 거꾸로 설정한 에러 해결

---

frontend/src/@components/@shared/Input/index.tsx
frontend/src/@components/@shared/Input/style.tsx
frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/coupon/CouponCreateForm/style.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponCreateForm/index.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponCreateForm/style.tsx
frontend/src/@components/user/UserSearchForm/index.tsx
frontend/src/@components/user/UserSearchModal/index.tsx
frontend/src/@hooks/ui/coupon/useCouponForm.ts
frontend/src/@hooks/ui/unregistered-coupon/useUnregisteredForm.ts
frontend/src/@pages/coupon-create-select/index.tsx
frontend/src/@pages/coupon-create-select/style.tsx
frontend/src/@pages/coupon-list/create/index.tsx
frontend/src/@pages/unregistered-coupon-list/create/index.tsx
frontend/src/@pages/unregistered-coupon-list/create/style.tsx
frontend/src/styles/globalStyle.ts

- Input.Counter로 개발을 진행하였습니다. 스타일을 공유하는 부분이 많고, 실제로 Input를 다루기에 요렇게 진행하였습니다!!!
- useCouponForm과 유사한 훅을 개발하였습니다.
- 주요 로직이 비슷하지만, 이는 언제든지 다르게 바뀔 수 있기에 이 후 변화에 쉽게 대응할 수 있도록 분리된 파일에서 개발을 진행하였습니다.
- CouponCreatePage와 유사한 페이지 컴포넌트를 개발하였습니다.
- 이 또한 주요 렌더링 로직, 스타일 로직이 유사합니다만 얼마든지 서로 다르게 바뀔 수 있는 `분리된 도메인` 영역이기에 서로 다른 컴포넌트로 개발합니다. 
- 위와 마찬가지입니다.
Resolves #429

feat: 미등록 쿠폰 생성 페이지

---

frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@pages/main/index.tsx
frontend/src/@pages/profile/login/index.tsx
frontend/src/Router.tsx

- v2 마이그레이션만 먼저 prod로 올리기 위하여, 구글 로그인, 미등록 쿠폰 기능은 숨겼습니다.

chore: 구글 로그인, 미등록 쿠폰 기능 감추기

---

backend/src/main/java/com/woowacourse/kkogkkog/auth/application/AuthService.java
backend/src/main/java/com/woowacourse/kkogkkog/auth/presentation/AuthController.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/UnregisteredCouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/UnregisteredCouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
backend/src/main/java/com/woowacourse/kkogkkog/member/presentation/MemberController.java

- 모든 서비스와 컨트롤러에 대해 생성자를 지우고 @RequiredArgsContructor를 추가한다.
Resolves #454

refactor: 컨트롤러, 서비스 빈들에 @RequiredArgsContructor 추가

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/dto/RegisterCouponCodeRequest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/UnregisteredCouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponDocumentTest.java
backend/src/test/java/com/woowacourse/kkogkkog/support/fixture/dto/UnregisteredCouponDtoFixture.java

- 미등록 쿠폰 등록 RequestBody 어노테이션 String을 요청 DTO 구현하여 교체
[@RequestBody Spring](https://velog.io/@wisdom08/RequestBody%EB%A1%9C-String-%ED%83%80%EC%9E%85%EC%9D%84-%EB%B0%9B%EB%8A%94-%EA%B2%BD%EC%9A%B0)

fix: 미등록 쿠폰 등록이 안되는 문제

---

frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/index.tsx
frontend/src/@hooks/@queries/unregistered-coupon.ts
frontend/src/@hooks/business/coupon.ts
frontend/src/@hooks/business/unregistered-coupon.ts
frontend/src/@hooks/ui/unregistered-coupon/useUnregisteredForm.ts
frontend/src/@pages/unregistered-coupon-register/IssuedRegisteredCouponPage/index.tsx
frontend/src/Router.tsx
frontend/src/apis/coupon.ts
frontend/src/apis/unregistered-coupon.ts
frontend/src/types/unregistered-coupon/remote.ts

- 쿠폰 Create 로직 추가
- 복사 url 수정
- 쿠폰 생성 후, 쿠폰 개수에 따라 라우팅 위치 조절
- 쿠폰 생성 성공, 쿠폰 등록 성공에 Toast 띄워주기
Resolves #478

feat: 미등록 쿠폰 세부적인 기능 개선

---

backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/CouponService.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/CouponsResponse.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepository.java
backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/coupon/domain/repository/CouponRepositoryTest.java
backend/src/test/java/com/woowacourse/kkogkkog/documentation/CouponDocumentTest.java

- 쿠폰 목록 반환에 페이지네이션을 추가
- 쿠폰 목록들을 반환할 때 무한스크롤이 가능하도록 기능을 추가했습니다.
DTO에 속성값을 추가해야해서 Response 페키지 위치가 변경되었습니다. 향후 의논이 필요할 것 같습니다.
Resolves #469

feat: 쿠폰 목록 반환에 페이지네이션을 추가

---

frontend/src/@components/@shared/Input/style.tsx
frontend/src/@components/@shared/SelectInput/style.tsx
frontend/src/@components/coupon/CouponCreateForm/style.tsx
frontend/src/@components/coupon/CouponHistoryItem/style.tsx
frontend/src/@components/coupon/CouponItem/big.style.tsx
frontend/src/@components/reservation/ReservationSection/style.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponCreateForm/style.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponItem/style.tsx
frontend/src/@components/user/UserSearchModal/index.tsx
frontend/src/@pages/coupon-list/coupon-detail/request/style.tsx
frontend/src/@pages/coupon-list/coupon-detail/style.tsx
frontend/src/@pages/coupon-list/index.tsx
frontend/src/@pages/download/style.tsx
frontend/src/@pages/unregistered-coupon-detail/index.tsx
frontend/src/@pages/unregistered-coupon-detail/style.tsx
frontend/src/@pages/unregistered-coupon-register/IssuedRegisteredCouponPage/style.tsx
frontend/src/@pages/unregistered-coupon-register/RegisteredRegisteredCouponPage/index.tsx
frontend/src/styles/theme.ts

- dark 변수명 오타 제거
- 사용하지 않는 import 제거
Resolves #498

refactor: 변수명 오타 제거

---

frontend/src/@components/@shared/Loading/index.tsx
frontend/src/@components/@shared/Loading/style.tsx
frontend/src/@pages/coupon-list/index.tsx

개인적으로 스타일 이슈가 존재하는 것으로 파악되어 진행하였습니다. 개발 중 케이스가 발견되지 않아 크기를 키우기만 하고 작업 종료합니다. (이후 니즈가 발생하면 다시 진행하겠습니다)
- 로딩 컴포넌트 수정
- 크기 확장 
Resolves #497

refactor: 로딩 컴포넌트 스타일 이슈

---

frontend/src/constants/coupon.ts
frontend/src/types/coupon/client.ts

코드 잘 짜두어서 대응할게 거의 없군요 하하~
Resolves #519

feat: RECEIVE 이벤트에 대한 메시지 추가

---

frontend/src/@components/coupon/CouponCreateForm/index.tsx
frontend/src/@components/coupon/CouponCreateForm/style.tsx
frontend/src/@components/unregistered-coupon/UnregisteredCouponCreateForm/index.tsx
frontend/src/@pages/coupon-create-select/index.tsx
frontend/src/@pages/main/index.tsx
frontend/src/@pages/unregistered-coupon-list/create/index.tsx
frontend/src/@pages/unregistered-coupon-list/index.tsx

- 일반 쿠폰 -> 꼭꼭 회원에게 쿠폰 보내기
- 미등록 쿠폰 -> 링크로 쿠폰 보내기
이 느낌으로 UX writing 바꿔보았습니다.
Resolves #521

feat: 미등록 쿠폰 UX writing 수정

---

frontend/src/@components/user/UserSearchForm/index.tsx

feat: 유저 검색에서 이메일 정보 제거

---

backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/CouponServiceTest.java
backend/src/test/java/com/woowacourse/kkogkkog/support/application/ApplicationTest.java

- `@Transactional` 삭제
- RandomPort 삭제
- `@Transactional`을 삭제하면서 update 메서드 이슈가 있어서 테스트코드 하나 수정했습니다.
Resolves #없음

refactor: @ApplicationTest의 불필요한 애노테이션 제거
